### ISSUE TITLE
Add initial support for git-integrated export

### ISSUE THREAD

**Issue by mmzmusicnotes** [joyfullservice/msaccess-vcs-integration#101]
- When files are exported, record the modified dates of all files changed at time of export - this should be every file in the project for first export or exports without fast save enabled, and only modified objects when fast save is enabled
- On subsequent export, files may be automatically overwritten so long as date matches and there are no pending changes (a "pending change" for this purpose is a file modified and unstaged, staged and uncommitted, or committed, which has not been updated by a previous import according to its modification date)
- If the HEAD commit has changed, or there are pending changes of any kind, prompt the user and warn them per file before proceeding (the warning may also have "yes/no to all" options)
- Changes in VCS version in .json headers can be ignored when exporting; investigate whether there are any other properties which should be ignored

(Note: If we adopt these requirements, update https://github.com/joyfullservice/msaccess-vcs-integration/wiki/Advanced-Git-Integration with them.)

**Comment by joyfullservice** [comment]
The **git integration** aspect seems to be tabled at this point. (To summarize, this is referring to using **git** to determine which files have changed, rather than referencing file modification dates.) We can reopen these issues in the future if there is interest in developing them further, but I am closing them out for now so we don't clutter up the issue pool with items that have no foreseeable completion date, and no developers actively pursuing them. Also closing #102, #103, #104, #105.
