### ISSUE TITLE
Add optional integration into the Access VBA environment

### ISSUE THREAD

**Issue by mmzmusicnotes** [joyfullservice/msaccess-vcs-integration#103]
- Add the ability to access the VCS interface directly within the Access VBA environment
- Ideally, a custom toolbar with options for import changes, export changes, and accessing the UI/settings would be ideal
- If that is unfeasible, entries on the Add-ins menu or similar would also work well
- If neither of those are feasible, commands from the immediate window would also work

**Comment by hecon5** [comment]
After some poking about, I've noticed the JSON functions are available to the referring database, but nothing else.

This will provide a useful rabbit hole to go down and figure out why they are, but no others are.

**Comment by joyfullservice** [comment]
@hecon5 - This is because the other modules use `Option Private Module` which makes the functions public to the add-in, but not to other projects. (I probably should add that line to `modJsonConverter` as well.)

If you are looking to invoke the add-in from a database, you might check out #88 which demonstrates the same demand-load effect as launching the add-in from the add-in menu and does not require a reference in the calling database.

Hope that helps!

**Comment by hecon5** [comment]
As I ponder this: is there a reason you don't want the addin's functions exposed to the calling database? I can see how not wanting most of them exposed would be a wise choice (the point of the addin is to have it /not/ be part of the code base).

Would having a few functions ( such as [exportsource], [launchscreen], [uninstallvcsaddin]) might be really useful for deployment. 

Because of the development environment I have, I cannot load addins to Access at large, and must reference them in the database itself; being able to remove this reference prior to deployment would be extremely nice.

I saw #88, and I think a "helper" function in my database will be needed (to load the reference, and then to remove it just prior to compiling to ACCDE and deployment); I'd like to keep the helper as small as possible, and be able to just call the requisite functions. 

Would moving those subs out of modAddin and into a "modAPI" (or similar) be something you'd consider? 

This could allow interfacing with the functions my app would need for users like me that can't load the addin to Access at large, and keep the rest out of view/developer's mind when dealing with a separate issue (I am a big fan of single-button abstraction to focus on the fixes that need to happen without having to deal with functions that really shouldn't be interfaced with directly).

**Comment by joyfullservice** [comment]
@hecon5 - Thanks for sharing the additional background on your interest in referencing vs. installing the add-in. I am not opposed to exposing the main functions to the calling database, but I had not encountered a use case where this was necessary, since it wasn't required when calling as an add-in. That being said, I do understand the constraints in your development environment, and would be happy to work with you on that.

Obviously the simplest solution is just to remove the `Option Private Module` from `modAddin`, but that would expose a lot of other functions that are really just intended for the internal use. I like the idea of the `modAPI` module, but I think I would prefer to keep the add-in functions all together in one place, from an organizational perspective, especially since the vast majority of users will be using it as an add-in vs. a referenced library. Instead, I would suggest adding some _wrapper functions_ in `modAPI` that call the functions in `modAddin`. Taking this approach keeps all the add-in logic in one place, and keeps the `modAPI` focused on the single purpose of exposing public functions to the calling database.

Perhaps you could create a new issue for this, (since this is taking a different direction than the original issue) and then you could create a pull request that closes the new issue after implementing the `modAPI` module.

P.S.
Just for a little more background on the add-in vs. library, if down the road you start using the functionality to build from source, things can get a little more tricky without using the application-level add-in. The neat thing about an application-level add-in is that it can remain loaded even after closing all databases. (As is the case when building from source where the original database is closed, and a new one is created.) But again, I understand that some users may be limited in the add-ins they are allowed to install in a corporate environment.

**Comment by hecon5** [comment]
I like the `modAPI` wrapper idea; it keeps in line with keeping interfaces concise, and the code together with relevant pieces. It would also allow one to add/remove interface parts without affecting any of the other code, which will be rather nice.

I agree with you on removing the `Option Private Module` from `modAddin`: exposing more than is required is a bad plan, and will probably lead to me (or someone else) with some heartbreak as we accidentally call something we didn't mean to. 

I'll make a new issue for the modAPI; I'll also post some of my ideas for the 'reference' module (I don't know I'll have all the functions in at first, but I'll be a start).
