### ISSUE TITLE
Fast save issue with Forms and backend code modified through "Replace All"

### ISSUE THREAD

**Issue by Indigo744** [joyfullservice/msaccess-vcs-integration#106]
Hello,

I found a weird bug when using the "Fast Save" option.

If I perform a "Replace All" in VBE on the whole project, the changes impacting some forms may not be exported.

It's quite easy to reproduce the issue:
1. Create a new DB
1. Add a form, with a button, with a Click event containing a MsgBox with a message
    ```vb
    Private Sub Commande0_Click()
        MsgBox "HELLO WORLD"
    End Sub
    ```
1. Save everything. Export to source.
   Check that the exported file contains the backend code.
1. Close all form, go back to the VBE, then use "Replace All"  for the whole project of WORLD to FooBar
   ![image](https://user-images.githubusercontent.com/7137528/100455751-8ac53980-30bf-11eb-9b87-1ff31e1893a3.png)
1. Save. It should ask if you want to save the form. Say yes.
1. Export to source again. 
   **Check that the exported file does NOT contain the new code with FooBar** 😞 

Looking at it, I think the main issue is that, when using "Replace All" from VBE without the form open, Access will NOT update the "last modified" property of the form. It can be checked by right-clicking on the form, and in Properties.

Sadly I am not sure how to fix this issue.

The easy workaround is just to deactivate "Fast Save", but I fear this can bite people who do not expect a change to be ignored when exporting.

A fix could be to check the VBA code from the .bas file against the current content but it wouldn't be so fast anymore...

What do you think?

**Comment by mmzmusicnotes** [comment]
What happens if you use replace all, then add a space, save, delete the space, and save again? Does making some pro forma edit like that cause Access to see the file as eligible for fast save?

**Comment by Indigo744** [comment]
If after replace all, I edit the code-behind (adding a space like you said) and saving, it actually works because I can see the form actually opening in Access...

But we cannot expect users to (a) know that, (b) actually do that if there are a lot of forms impacted 😅 

Sadly, I fear this is another Access limitation that we will need to live with. The "last modified" timestamp cannot be relied upon to detect pending changes... 😞

**Comment by joyfullservice** [comment]
There is a possibility to explore here... These kinds of code changes involve the _VBE components_, which can be read and/or exported independently of the parent objects. (I.e. you can export the code module from a form through VBE, independent of the `Application.SaveAsText` operation. It is possible that we could either (a) read the code module contents or (b) export the code module to a file, and then generate a hash that could be used to detect changes. My hunch is that this would be faster than exporting the entire object (and _WAY_ faster if the parent object had embedded images or other large binary data) and might still give us reasonable performance when comparing to our saved state of the object in `git-sync.json`.

On the performance side, I have another idea as potential here that I will go ahead and mention. [There is a way](http://www.excelhero.com/blog/2010/05/multi-threaded-vba.html) with VBScript files to pass data to worker scripts so that they can process in parallel and return data back to the calling application. I have implemented this with great success on another Access system that retrieved shipping rates when updating items in the cart. The API call to retrieve shipping rates was called by the independent process in the script file, and passed back to Access after the call completed. If we end up needing to generate hashes on files to compare changes, this might be a great way to generate the hashes in parallel while the other export processes are running to reduce the overall run time on the script. (And utilize additional threads for generating the hashes.)

**Comment by Indigo744** [comment]
@joyfullservice interesting take!

If I follow you, we should:
- Export `Form` as before with `Application.SaveAsText`, but now strips out VBA code
   We can still check "last modified" datetime to detect pending changes.
- Read `Form.Module` and write it to a different file
   We can use a hash to detect changes before writing the file

I have a couple of questions:
1. Should we really use another file? We could try to locate the code-behind but we would essentially output twice the content?
1. How should we name this new file?
1. Which hash should we use?

**Comment by joyfullservice** [comment]
Close... I was thinking of exporting the VBA directly from VBE, like this:

```vb
Public Sub TestVBEExport()

    With VBE.ActiveVBProject.VBComponents("Form_frmVCSMain")
        .Export "code.bas"
        Debug.Print .CodeModule.Lines(1, .CodeModule.CountOfLines)
    End With

End Sub
```

This would only be used to check for changes not reflected in the object's modified date. The `SaveAsText` version of the file would still be the primary source file for version control. The advantage of the VBE export is that it would (potentially) be faster than exporting the entire object, and should contain any (VBA code) changes not reflected in the parent object's modified date.

As to the hash, we could use any hash algorithm that would detect changes in content. I was thinking of SHA1 (I think this is what Git uses) or MD5 (often used to verify file downloads) using the [built-in Windows cryptography functions](https://stackoverflow.com/a/17858040/4121863).

**Comment by Indigo744** [comment]
Oh I see 😺. 

After `SaveAsText`, should we store the hash somewhere for fast retrieving without having to read the current file? If yes, where?

As a side note, MD5 would suffice (since we're talking about file hashing, and there's little probability of collision) but the `MD5CryptoServiceProvider` may be deactivated in Windows if FIPS mode is activated (which may be the case in some specific corporate environment). Hence `SHA1CryptoServiceProvider` should be preferred.

**Comment by mmzmusicnotes** [comment]
I would also second SHA1, but for security reasons. While we are only trying to handle accidental conflicts here, so the risk is low, MD5 isn't really suitable for general use anymore.

**Comment by joyfullservice** [comment]
The initial implementation of the Sha1 verification on a `CodeModule` object was a success. It detects find-and-replace changes that are not reflected in the `DateModified` property. It seems pretty fast... On a small module I was seeing 0.5 seconds for 1000 iterations, while a 2.5K line module was more like 3.7 seconds for 1000 iterations. Exporting to a file and running the Sha1 on the file was more than 10x slower.

I am also thinking of limiting the Sha1 hash to the first 7 characters, similar to what GitHub does. This would make the cache file smaller, and a bit more readable. If I understand the math correctly, this would have almost [no chance](https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection) of ever causing a problem in our implementation. Does that sound reasonable?

**Comment by Indigo744** [comment]
I have no problem with using a truncated version of SHA1 (and I think you meant "similar to what _Git_ does"!).

The only thing is, you are doing this in the `git-integration` branch? Is there any chance to get these improvements in main branch before the Git integration is done? 😉

**Comment by joyfullservice** [comment]
@Indigo744 - Yes, you are right, it is Git that truncates the hash.  😄

Regarding the `git-integration` branch, my thought there is that by doing the major refactoring in another branch, we won't need to worry about creating upgrade paths for each iteration of the development process, since it will only be used by a few developers in active development and testing, not in general production use. (I.e. we might change the names of some of the export files or the structure of the cached state several times before we settle on the final version.) This also allows us to easily release fixes for the master branch to address issues in the general release while continuing development in the new branch.

You should be able to switch to that branch, build from source, and be right up-to-date with the latest commits. I was thinking that you and @mmzmusicnotes would also have the option of creating pull requests targeting the `git-integration` branch as we build out the git integration. I am a bit new to some of the more advanced branching/merging in git, so let me know if there is a better way to do this.  😄  Again, my goal is to allow efficient collaborative development on a branch that is independent of the primary general release (`master`) branch. [These](https://stackoverflow.com/questions/4470523/create-a-branch-in-git-from-another-branch) two [links](https://stackoverflow.com/questions/9135913/merge-pull-request-to-a-different-branch-than-default-in-github) might be helpful...

**Comment by A9G-Data-Droid** [comment]
I would like to discourage the truncation of SHA1 values. Collisions are possible even with a full SHA1. The U.S. National Institute of Standards and Technology has banned the use of SHA-1 by U.S. federal agencies in 2010 after it was shown that collisions could be created on purpose.

I would recommend using SHA2 and keeping the full hash. Modern CPUs have hardware acceleration for crypto functions. I wouldn't worry about the performance.

**Comment by A9G-Data-Droid** [comment]
@joyfullservice I understand that it is not used for cryptography but FIPS mode doesn't care. I, like hecon, run in a FIPS controlled environment and programs that call SHA1 .net libraries just crash regardless of why it was used. Instead of working around that by using a library that is not blocked we are supposed to only use FIPS approved algorithms because US Government. I would rather not have to document and explain every usage of SHA1 to an auditor. It's easier to just avoid that conversation.

Making it an option is fine. Then users can choose to select a FIPS validated SHA2 or SHA1 for speed. We can then easily show real world performance impact with your testing suite. My main point is that neither should be truncated as that compromises the effectiveness with absolutely no benefits.

**Comment by joyfullservice** [comment]
Thanks for the clarification on the FIPS requirement. I can certainly see how this would be important for you. Does SHA256 meet the FIPS requirements? If so, it doesn't look like it would be too difficult to implement this...

**Comment by joyfullservice** [comment]
Working on this now...

**Comment by joyfullservice** [comment]
Interesting... I am not seeing any performance difference in real-life exports when using SHA256. That being the case, we can probably just make that the default. I should be able to push the changes this afternoon...

**Comment by A9G-Data-Droid** [comment]
It works but I'm seeing short 7 character hashes in the index. We spend the cycles to calculate the whole thing. Why not store it?

**Comment by joyfullservice** [comment]
You can, just uncheck the option for short hashes and you will get the full hash.

**Comment by joyfullservice** [comment]
I am going to close this issue out as it has been fully resolved through the hashing of the VBA code module and has been rolled out to the general release.
