### ISSUE TITLE
Create modAPI to expose selected routines to referencing db

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-integration#117]
Create a modAPI to wrap interface routines to referencing database as per #103; this will be helpful where users are not able to install the addin at the application level and are required to load it at the database level (corporate/gov't/etc. users).

**Comment by hecon5** [comment]
With the pull request merged, are there any other functions in the API that should be exposed? if not, this can be closed, I think.

**Comment by joyfullservice** [comment]
This morning I had another idea on how to do this in an even more elegant way. Rather than trying to include "VCS" in every command and have them mixed in with all the other available commands, I am using `modAPI` to expose a single `VCS` object from which autocomplete can list very clear and succinct properties and methods with no concern of ambiguity or name collision.

![image](https://user-images.githubusercontent.com/7254992/104509417-41697480-55af-11eb-8bbd-41305a0b6c72.png)

Going forward, you should be able to use the `VCS` object to easily reference properties and methods specific to VCS. I also exposed the `Options` class through this so you can read or even change options before running an export. (If you change an option, you will also need to save it before running an export.)
