### ISSUE TITLE
Form should be resizeable

### ISSUE THREAD

**Issue by Tanarri** [joyfullservice/msaccess-vcs-integration#143]
Hi,

first: thanks for all your work!
The last days I had 2 issues and all are resolved by you (but not yet testet by me on my computer)
I  had developed the last years my own Import/Export Tool for Access with SVN Integration but I will throw it away and will use yours (If you are interessted I can mail you it privatly.. Perhaps there are things you could use or ideas which a interessesting)

Issue with your V3.2.2
The Forms are not resizeable. Perhaps you could change this, because some controls my be too small to show the content

![Zwischenablage01](https://user-images.githubusercontent.com/6181166/106252087-1f5e2c00-6216-11eb-9e50-7a97dcad7d3d.png)

In my Access-Project I use the Feature and it works quite well
![Zwischenablage02](https://user-images.githubusercontent.com/6181166/106252228-52082480-6216-11eb-8006-bd0cf1806f3f.png)

**Comment by hecon5** [comment]
I've thought this, too; but executing it proved to be difficult as it would require some of the controls to resize dynamically. 

Can you give it a go on dev and make a PR? I'll try it out on my end (unless @joyfullservice  beats me to it, he seems much faster than I at many things).

**Comment by joyfullservice** [comment]
The built-in resizing tools are pretty neat! A huge improvement over the older versions where you had to do all that through code.  😄 I actually have resizing set on the main form, using the tools @Tanarri shows in the screenshot above.

For the options dialog, most of the options really wouldn't be helped by resizing, since most of them are checkboxes or descriptions. As an alternative approach for extra long table names, I have adjusted the size of the table name box so you can see three full rows of text. That should handle names as long as 60+ characters, and you can select inside the box to see names even longer than that. (Although there might be some other design considerations if table names get that long...  😄 

I will go ahead and push an update with the larger text box size as pictured below. @Tanarri - Does this work better for you?

![image](https://user-images.githubusercontent.com/7254992/106345095-50b91500-6273-11eb-927b-16610aa7f915.png)

**Comment by joyfullservice** [comment]
I will go ahead and close this issue, unless there is something further we need to do here.
