### ISSUE TITLE
Remove Nag for legacy VCS after first prompt

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-integration#148]
I dislike too many prompts for users (especially ones I have to keep clicking through).

Would like to be reminded once, then have the option to turn the legacy VCS 'nag' off for subsequent exports. This will simplify "exportallsource"

**Comment by hecon5** [comment]
This is completed with PR#148; closing now.

**Comment by joyfullservice** [comment]
Hopefully you don't mind a couple changes that I made in 19466cd. From a cognitive processing load, it is more disruptive to the user to have to stop and understand a brand new concept and make a decision during the export process. I simplified this to simply notify them of the new option available in settings. After clicking through the message a few times, they will probably stop and read it, and then go ahead and change the option. If they save the option as default for new projects, they won't see it again at all. Otherwise if they just save it for the current project, it will be off for that project, but will come back in other projects that may contain the legacy code. I feel like this will give us the best of both approaches having an option to turn off the suggestion, but making the prompt more clear to the user.

![image](https://user-images.githubusercontent.com/7254992/106633531-8cd6c900-6544-11eb-93ef-5ee3dcef50e3.png)

Thanks again for your contributions! This was a good idea. I hadn't considered that some people may want to run with both systems for a period of time while testing the VCS add-in. 😄

**Comment by hecon5** [comment]
Awesome, I wasn't sure what to do about that; I wish there was a msgbox that let you have a check option like other front ends do, but landed at two. Yours is more seamless, especially for users that will excise the code right pronto. 

On top of our migrating to the addin, we've also "adopted" some of the modules and integrated them into our database (partially out of "efficiency" and partially out of reduction in code base management), so being able to turn it off will be important while we fold those out into more concise module/classes.
