### ISSUE TITLE
Compile error when building dev branch from source (See comments for fix)

### ISSUE THREAD

**Issue by Tanarri** [joyfullservice/msaccess-vcs-integration#163]
Hi,

I have downloaded and installed the V3.2.2 and checked out the dev-branch of "msaccess-vcs-integration" with "GitHub Desktop"
Then I have builded the dev-branch with "build from source".

All right

But whn I start the builded "Version Control.accda" a error 7960 occurr
![Zwischenablage02](https://user-images.githubusercontent.com/6181166/107162007-bce8f680-69a0-11eb-9687-311219a07f02.png)

Then I opened the vba editor and saw the module "modConstants" was imported wrong. I think the encoding has a error
![Zwischenablage01](https://user-images.githubusercontent.com/6181166/107162038-e1dd6980-69a0-11eb-9b39-9c72d8de73c3.png)

Greetings
TanarRi

**Comment by joyfullservice** [comment]
Those are from the UTF-8 BOM that is now included in the export files. If you manually remove those characters from the two affected modules, then restart the database, it will start normally. Then install to update the installed version. Then you should be able to build from source like normal.

**Comment by hecon5** [comment]
I actually had this issue, too; I also had to revise the `UTF8_BOM` and `UCS2_BOM`, also before the thing would build correctly.

**Comment by joyfullservice** [comment]
Basically the issue here is that the previous version of the add-in is not expecting a BOM in a module file. The latest add-in can export and build the project just fine, so we are talking about a one-time change of manually removing the BOM before building the project for the first time. The other extended characters in these two modules will be replaced with the correct versions the next time the project is built from source using the updated add-in.

### To resolve the issue in building the `dev` branch for the first time after 9d6b7ff, 3b4b0df, etc... perform the following steps:

1. Build from source
2. Open the newly built add-in file. (You will encounter a compile error on startup.)
3. Manually remove the BOM characters from the top lines of `modConstants` and `modUnitTesting`. (No need to change anything else.)

![image](https://user-images.githubusercontent.com/7254992/107242212-5b9d4380-69f1-11eb-9842-e2a2a347dac9.png)

4. Compile and save the project. It should compile with no errors now.
5. Close and open the add-in again. It should now present you with the normal install screen.
6. Install/Update the add-in.
7. Build the project from source again. This time it should build and run with no issues.
8. Install the newly built add-in.

At this point you should be up and running with the latest version and not encounter this error again. 😄 I know this a few steps to walk through, but it should only affect a few of us that are actively developing on the `dev` branch. Later when this is merged back into Master, we will have a binary that includes the UTF-8 support, and will not encounter any issues building from source.

**Comment by hecon5** [comment]
@joyfullservice, as I think about this: this seems like a decent place to release a new (minor?) version for, or at least incorporate this change into the master? 

Also, what's your roadmap look like for the next release look like?

**Comment by Tanarri** [comment]
@joyfullservice, issue is fixed, when I do it like you described in https://github.com/joyfullservice/msaccess-vcs-integration/issues/163#issuecomment-775239424

**Comment by joyfullservice** [comment]
> 
> @joyfullservice, as I think about this: this seems like a decent place to release a new (minor?) version for, or at least incorporate this change into the master?

I agree. It would be good to work the UTF-8 module support into a release on the `master` branch so that anyone can build the `dev` branch without encountering errors.

> 
> Also, what's your roadmap look like for the next release look like?

Great question! I have created a new discussion here #164 where we can discuss that further.

**Comment by hecon5** [comment]
@Tanarri, @joyfullservice: now that dev/master have been updated, should this be closed, as it might be a moot point? 

Or is joyfullservice#186 related to this and once they're fixed/merged into master is when we should close this?

**Comment by joyfullservice** [comment]
I believe this is fully resolved following the merge of `dev` into `master`, and the subsequent release.

**Comment by Tanarri** [comment]
Is resolved
