### ISSUE TITLE
QuickSort optional arguments are broken

### ISSUE THREAD

**Issue by Ik-12** [joyfullservice/msaccess-vcs-integration#166]
Handling of optional parameters in `QuickSort` function (`modFunctions`) does not work 
because arguments `inLow` and `inHi` are not `Variant` (`IsMissing` works only with `Variant`):

```
    If IsMissing(inLow) Then inLow = LBound(vArray)
    If IsMissing(inHi) Then inHi = UBound(vArray)
```

This causes that collections are not properly sorted during export which in turn 
leads to irrelevant changes for example in `hidden-attributes.json`. 

Another potential issue related to sorting is that sorting order depends on the locale setting
of the database which again causes irrelevant changes when importing/exporting on machine 
with different locale settings. Unfortunately I do not have any good solution for this.

To reproduce the problem:

```
Dim arr() As String
arr = Split("u i a")

QuickSort arr
Debug.Print Join(arr, " ")
```

**Comment by joyfullservice** [comment]
Thanks for pointing this out! I have pushed a commit to resolve this issue in the `dev` branch. (And added a simple unit test using your sample code.)

**Comment by joyfullservice** [comment]
> Another potential issue related to sorting is that sorting order depends on the locale setting
> of the database which again causes irrelevant changes when importing/exporting on machine
> with different locale settings. Unfortunately I do not have any good solution for this.
> 

Yes, I am not sure of a good solution for this either. It seems that users would want to see things naturally sorted using their own locale settings, so the only real challenge would be where two developers are working on the same database using different locales on their development machines. I generally always use `Option Compare Database` in my code modules, which seems like it would potentially help, since technically both development databases _should_ be using the same sort order. But I obviously have not personally tested this.

Based on the fact that this would be a very unusual case, and the fact that we don't really have a reasonable solution in sight, I think I will just close this issue out based on the above fix, and we can open a new one to address the locale sort order if needed in the future.

Thanks again for helping resolve the sort issue! It is many contributions like this over the years that have made the add-in what it is today.  😄

**Comment by Ik-12** [comment]
Yes, explicitly sorting the collections on export should eliminate the problem in 99% of cases. 

(And sorting is really required when exporting: the order of objects in the database containers seems to vary
from machine to machine. For example, in our database form objects are in different order on my and my colleague's
machine although Office version and all locale settings are identical. )

**Comment by Ik-12** [comment]
And thanks for the quick fix. :)
