### ISSUE TITLE
ExportAllSource will delete unchanged files

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-integration#179]
@joyfullservice: With recent update, the `exportallsource` with `blnFullExport` set to `FALSE` will delete `tables` not changed from the directory. 

Looks like `FastSave` uses the same export flush/delete for the folders and while it (correctly) doesn't process the output file, it also deletes the previous one.

**Comment by joyfullservice** [comment]
I was able to reproduce this is the testing database... I will check this out and hope to push a fix shortly...

**Comment by joyfullservice** [comment]
Looks like the problem is with the `ClearOrphanedSourceFiles` function. It is making a couple assumptions that are not always correct. I am going to rewrite this function to handle cases where object types may have several different possible file extensions. (For example, tables may be represented as `.bas`, `.xml`, or `.json` files.)

**Comment by joyfullservice** [comment]
I just uploaded a new release to address this issue. Thanks for the bug report!

**Comment by hecon5** [comment]
huzzah! Thanks! Been frantically trying to get another project off my plate, so I'm glad you could take it.
