### ISSUE TITLE
FieldsIdentical function should test object parameter type

### ISSUE THREAD

**Issue by joyfullservice** [joyfullservice/msaccess-vcs-integration#2]
At present you can hit an error when exporting an index definition. Need to change this function to use generic object types, and use typeof to compare objects before looping through collections.

![image](https://user-images.githubusercontent.com/7254992/62575042-78d2de00-b85f-11e9-897e-30e0a59f8e8a.png)

**Comment by A9G-Data-Droid** [comment]
Found in: [modTable.bas](https://github.com/joyfullservice/msaccess-vcs-integration/blob/master/Version%20Control.accda.src/modules/modTable.bas)

The pull #5 will change the parameters to Object type but the iterator is still DAO.Field
Maybe it needs to be changed too but I haven't been able to reproduce the issue.

**Comment by A9G-Data-Droid** [comment]
The latest pull changes both the parameters and the iterators to type _Object_ so that anything can be passed in. I do not have any typeof comparison yet because I do not have the ability to reproduce the original error. Please test. If you have a minimal reproducible error case I can test it myself.
