### ISSUE TITLE
Export with Attachment object failed

### ISSUE THREAD

**Issue by GeekMustHave** [joyfullservice/msaccess-vcs-integration#209]
I just discovered this add-in and gave it a try with a small database I use for TimeTracking.  I'm getting an error when exporting data from the table with an Attachment object in it.  If I don't export the data then the process completes.

![image](https://user-images.githubusercontent.com/15093825/113443521-26451e80-93c0-11eb-8f57-51e58fce7ed3.png)

Here is the structure of the Table mentioned.

![image](https://user-images.githubusercontent.com/15093825/113443694-7ae89980-93c0-11eb-9189-47e629642aad.png)

While using Attachments fields is discouraged I have a number of inherited databases that use this data construct. 

Does your add-in support exporting the data from a table with an attachment in it?

**Comment by joyfullservice** [comment]
@GeekMustHave - I am glad you found the project! I hope you find it useful. The main idea behind this add-in is to export the **_structure_** of a database (source files) so that you can manage the development of the project in a version control system like GitHub/GitLab/SVN/etc...

It's not really intended to be a backup of the **_data_** in your database. That is something that you would want to do using a backup program or other tool. That being said, sometimes there are structural parts of a database such as a custom ribbon menu or a settings table that a user might want to include in the source code repository, so you do have the option to select tables that you would like to include in the export. The table data export is fairly basic, with a couple options for TDF or XML format, but it isn't really designed to support something like embedded attachments.

I hope that helps!

**Comment by GeekMustHave** [comment]
Thank you very much, that makes sense.  Thre are a few projects with Setting/Config values that would be candidates for backing up.

Thank you for your efforts to develop such a great tool for us lowly Access developers  ;-)
