### ISSUE TITLE
Error when trying to install the add-in

### ISSUE THREAD

**Issue by petrukio** [joyfullservice/msaccess-vcs-integration#220]
When I try to install the add-in by form the following error pops up.

![image](https://user-images.githubusercontent.com/81861187/117734825-9ec2aa80-b1ca-11eb-81df-7074416bb110.png)

![image](https://user-images.githubusercontent.com/81861187/117734218-61115200-b1c9-11eb-8be8-9f30bbb4f699.png)

Even trying to install by the traditional way (add-in manager) another error appears:
![image](https://user-images.githubusercontent.com/81861187/117734308-928a1d80-b1c9-11eb-98f2-22da2f633baa.png)

Below are the info about my environment:

Access Version: Office 365 MSO (16.0.13127.21452) - 64 Bits
Windows 10 Pro - 64 Bits
Version-20H2

**Comment by joyfullservice** [comment]
@petrukio - It sounds like you probably have your VBA options set to **_Break on All Errors_**. This add-in is not designed to function with that configuration, since many places in the code use `On Error Resume Next` and then test for specific error conditions.

I would personally recommend setting this option to **_Break in Class Modules_**. This works very well for me in my own development work and allows debugging of both modules and class modules while still honoring the error handling directives.

![image](https://user-images.githubusercontent.com/7254992/117738414-931eb600-b1c1-11eb-86d7-a1e2f26de241.png)

For further reading, you can check out [this article](https://www.fmsinc.com/tpapers/vbacode/debug.asp) from FMS that describes some more advanced debugging techniques.

Let me know if this resolves the issue for you!

**Comment by petrukio** [comment]
Thank you. It solved the problem. By the way, is possible you add a feature for a multi-language version? I mean, the possibility of translation for another language in a collaborative way using an XML file for instance.

**Comment by petrukio** [comment]
> @petrukio - It sounds like you probably have your VBA options set to **_Break on All Errors_**. This add-in is not designed to function with that configuration, since many places in the code use `On Error Resume Next` and then test for specific error conditions.
> 
> I would personally recommend setting this option to **_Break in Class Modules_**. This works very well for me in my own development work and allows debugging of both modules and class modules while still honoring the error handling directives.
> 
> ![image](https://user-images.githubusercontent.com/7254992/117738414-931eb600-b1c1-11eb-86d7-a1e2f26de241.png)
> 
> For further reading, you can check out [this article](https://www.fmsinc.com/tpapers/vbacode/debug.asp) from FMS that describes some more advanced debugging techniques.
> 
> Let me know if this resolves the issue for you!

Thank you. It solved the problem. By the way, is possible you add a feature for a multi-language version? I mean, the possibility of translation for another language in a collaborative way using an XML file for instance.

**Comment by hecon5** [comment]
@petrukio, see joyfullservice#87 for localization issue.
