### ISSUE TITLE
Strip SQL comments during forced SQL import

### ISSUE THREAD

**Issue by bodywithoutorgans** [joyfullservice/msaccess-vcs-integration#221]
I have a workflow, when all the queries are edited solely in external tool. It would be nice to be able to have comments in sql code and still be able to do the forced SQL import without changing the files themselves.

**Comment by joyfullservice** [comment]
As you are probably aware, this is a [limitation](https://stackoverflow.com/questions/3152424/how-do-i-comment-sql-code-out-in-microsoft-access) in Access JET-SQL.

One way you could approach this is to put your queries in a different folder, then create your own custom code to parse the SQL source files (removing comments) and write the SQL to the database objects. You could then call this using [Run Sub After Build](https://github.com/joyfullservice/msaccess-vcs-integration/wiki/Options#build).

Since comments are not supported in the actual database object that we are exporting, I would rather not (in the core system) add the complexity of trying to parse extraneous information added to source files that does not exist in the original export.

**Comment by hecon5** [comment]
I agree; as loath as it is to lose your comments in Access (I like using external editors, too); I don't think this should be in the scope of the Addin, either.  

This, among other reasons, is a big reason I moved to using nearly 100% dynamic pass-through queries and/or setting up a view or stored procedure on my SQL server instead, because pass-through queries DO support comments (JET doesn't bother parsing, just hands them over to the server), they're *usually faster, and I can use my external editor and a fancy pants (ugly as sin but fully functional) converter I made to move SQL code into "VBA Module Code" that I hand through.
