### ISSUE TITLE
Wiki link to Options/md page is broken

### ISSUE THREAD

**Issue by jhgarrison** [joyfullservice/msaccess-vcs-integration#280]
On page https://github.com/joyfullservice/msaccess-vcs-integration/blob/master/Wiki/Documentation.md, the link to Options at the bottom of the page points to `..../Options` instead of `..../Options.md`.

**Comment by joyfullservice** [comment]
Thanks for pointing this out! It looks like maybe you were accessing the Wiki pages through the source folders rather than from the Wiki tab.

![image](https://user-images.githubusercontent.com/7254992/140756192-98585101-9192-491d-b406-ac17b3b1bcde.png)

I set up a copy of the Wiki pages in the source code section so we could more easily collaborate on changes and to give me the opportunity to review proposed changes. For general browsing of the wiki information, I would recommend using the Wiki tab. If you have suggested changes for the wiki documentation, you can submit these as pull requests in the Wiki source code folder, and I can mirror these changes over to the Wiki tab.

Hope that helps!
