### ISSUE TITLE
Run Time Error 3032

### ISSUE THREAD

**Issue by kocivan** [joyfullservice/msaccess-vcs-integration#29]
Hi,
Thanks for the application. 
But I get the error that appears in the attached pictures. I'm using office 365 64 bit.

![2020-05-24 (1)](https://user-images.githubusercontent.com/65854444/82753599-78480b80-9dcf-11ea-8c12-8fef07ecf1f8.png)

![2020-05-24](https://user-images.githubusercontent.com/65854444/82753597-754d1b00-9dcf-11ea-8311-97be826d2db2.png)

**Comment by joyfullservice** [comment]
@kocivan - Thanks for reporting this issue! If you can adjust a setting in your VBA Options, it will allow us to see where the error is happening in the code...

![image](https://user-images.githubusercontent.com/7254992/82829720-8ce0de00-9e79-11ea-9f58-ac1a53eaf4de.png)

By default, the VBA debugger shows the error at the calling function instead of the class module where the error actually occurs. Changing this option allows the error handling to break inside the class module where we can pinpoint the error more specifically.

**Comment by kocivan** [comment]
Hi, @joyfullservice thank you for answering
I changed the setting, and result
![2020-05-25](https://user-images.githubusercontent.com/65854444/82835223-0ef9f280-9ecc-11ea-9fc9-b47792000331.png)

**Comment by joyfullservice** [comment]
This should be fixed in the latest release. Let me know if you encounter any further problems with it!
