### ISSUE TITLE
Export/Import of table with image data not correct

### ISSUE THREAD

**Issue by ad26495** [joyfullservice/msaccess-vcs-integration#305]
I recently found your tool: great  tool and I am happy to use it.

Last week, I stumbled on a (minor) issue  in version 3.4.19:
I have a local table containing records with images (icons in this case).
In the options for export, I have selected this table to include its data, in XML format.
When this table is imported back (via build-from-source), the data in the table is now useless. Before export the table showed "image" in all records; after import it shows "binary data" in all records.

Can you please check?
Thanks, Alex

**Comment by joyfullservice** [comment]
Hi Alex,

I did a little test on this, and it appears that the internal Access function does not correctly import embedded OLE images after exporting to XML.

To reproduce the issue:

Create a column in an internal table with `OLE Object` data type.

![image](https://user-images.githubusercontent.com/7254992/155343421-b62b18b2-91d0-47e9-bfa7-b19260ff76e5.png)

Paste an image into a record. You will see `Picture` displayed.

![image](https://user-images.githubusercontent.com/7254992/155343010-23a498dc-6355-46fe-bf5b-145b98727ee9.png)

Use the following lines of code to export the data as XML.

```vba
ExportXML acExportTable,"tblAttachment","raw.xml"
```

Delete the existing record in the table, then import the record from the XML file.

```vba
ImportXML "raw.xml",acAppendData
```

The field now lists this data as Long Binary Data instead of Picture, and the content is no longer usable.

![image](https://user-images.githubusercontent.com/7254992/155344440-016d737b-3e20-4f4f-9c92-199004b61b20.png)

### Conclusion

This appears to be a bug in Microsoft Access itself, not the add-in code. Unless I am missing something here, it looks like the native Access `ExportXML` and corresponding `ImportXML` functions do not fully support OLE Object content. Columns with attached files do not appear to work very well either, as the data hits size limits and gets truncated pretty easily. (I am seeing this in Microsoft Access 2010, and I assume this to be the case in later versions as well.)

I don't know the context of your project, but I might suggest using the shared image gallery for storing these icons. This is fully supported by the add-in, and can probably be used in a very similar way in your application.

![image](https://user-images.githubusercontent.com/7254992/155346548-13699214-7b67-4b86-b955-5958301cf57c.png)

If there was sufficient need in the Access developer community, we could potentially develop a way to handle this type of embedded OLE content and attachments. That being said, the priority might not be as high because that tends to go towards the handling of data vs. the export of structure and definitions that this add-in is primarily focused on.

**Comment by hecon5** [comment]
I agree @joyfullservice; handling this would be a decently difficult undertaking; and because shared images are already handled in the addin via the built in tool, I'd think it'd be fairly rare to have that data be elsewhere as the shared image tool is already a built in feature.

If we did do something like that, I'd expect it to be based on that export/import mechanism and not to roll your own.

@ad26495, is there a reason you're using OLE fields in lieu of the shared images tool Access already has?

**Comment by ad26495** [comment]
Thank you for investigating so promptly.

The reason is that I did receive this table (with the icons) as part of a code from someone else.

I understand your arguments, and will look into moving this to shared images (or another solution).
As far a I am concerned, the issue can be closed.

Thank you,
Alex

**Comment by joyfullservice** [comment]
> 
> The reason is that I did receive this ... as part of a code from someone else.

I understand!  😄 I would guess this is probably something that every Access database developer deals with somewhere along the way. Thanks for bringing this to our attention.

- Adam
