### ISSUE TITLE
Access not responding while build from source

### ISSUE THREAD

**Issue by Keurdis** [joyfullservice/msaccess-vcs-integration#307]
Hello,

I work with 2 other personne on a projet made with access 2016 , we work separately on different feature . I've merge our different version of the code but i have a issue when i try to rebuild the projet .
When i launch the build from source, at "importing tables" stage Access past to " Not responding" state . After around 10 000sec  / 2h30, access come back to us and the message "done. (with the time of the operation) " write on green but the file stay unusable ( the different table stay but all the source code is gone) the weight of the file have past of 12Mo to 500ko.

We work with a link tables locate on a network drive ( maybe that it cause this mistakes ? ) we also have 2 tables export in XML format  
I've try to launch the build step by step but it's very too long.
I don't have any error message and i am little lost so i ask your help.
I stay at your service if you have so more questions.
Thanks to you.

**Comment by joyfullservice** [comment]
Hi @Keurdis,

Thank you for posting the details on this issue. I am glad to hear of how you are using the add-in to allow multiple developers to work on different parts of the same project. That is exactly what it is designed to do.  😄 

I have a few more questions for you...

- What version of the add-in are you using?
- You mention that you are using a linked table to a network drive. What kind of linked table is this? Is it a Microsoft Access table in another database, or another type of file?
- How many linked tables do you have in your project?
- What is the language setting of Microsoft Office?
- What is the language/locale setting for your computer?
- Do you see any errors in the `Build.log` file after the build process? (Or maybe that file does not get created.)

Here is something that may be helpful when troubleshooting this issue:

Create a very simple, empty database on your computer. Link to one of the tables on your network share. See if you can export source and build from source on this very simple test. If it works, add in some more things, like the table data XML export. As you slowly add in different pieces, you can see exactly which part causes the problem.

After you discover where the problem comes from, then see if you can create a simple database that demonstrates the problem. Make sure it does not include any of your company data or network security information. If you can attach a zip file with the databases, I can test it on my system and see if I encounter the same problem.

I hope that helps!

**Comment by hecon5** [comment]
Linked tables are HORRIBLE for build time; speaking from experience. We have "just" ~200 linked tables to an SQL server (the time to link an SQL server is considerably faster than a file-based linking like to an Access DB backend, which in testing is 3-5x slower per linked table connection (or more, see below)), and it takes 5-20 minutes for me to build an SQL-linked database front end depending on various elements. I would imagine a similarly sized Access backend would be considerably slower.

When we build, it "hangs" at the table linking step for a long time, and doesn't appear to do anything. 

Some additional considerations to @joyfullservice's suggestions (all of which are good and will help figure out the solution).
- Are there geographical differences between your machine and the server you're talking to? For instance, our sql server is on the other side of the country from me). Speed of light is VERY fast, but at that scale, it makes a BIG difference.
- Are you using VPN (this may impact network speed, and routing, which adds to the geographical component above).
- How BIG is the backend file? I've noticed with many cases the larger the backend file (used for us only during some build out testing) the larger backend files do make a difference.
- Turn on "[Show Detailed Output](https://github.com/joyfullservice/msaccess-vcs-integration/wiki/Options#general-tab)" When building, I've noticed this updates the screen more often (once each table), so you can see progress, and helps to ensure it's still going vs truly crashed.

**Comment by Keurdis** [comment]
Hello joyfullservice, Hecon5,
Thanks for your answer, 

For @joyfullservice question

What version of the add-in are you using?
       - I use the version 3.4.19 , i have tryed in a other computer on 3.4.20 but nothing change

 You mention that you are using a linked table to a network drive. What kind of linked table is this? Is it a Microsoft Access table in another database, or another type of file?
     - We work with .accdb file 

How many linked tables do you have in your project?
    - We have 94 linked table shared on 9 different .accdb files

What is the language setting of Microsoft Office?
    - Language setting of Office is in French

What is the language/locale setting for your computer?
   - Same thing for the computer

Do you see any errors in the Build.log file after the build process? (Or maybe that file does not get created.)
    - The file Build.log have not creating but i didnt see a error message after the build on VCS windows , just A LOT on white space with sometime 2 or 3 "random ?" caracter and the line "Done" at the end 

I will try your solution in the day, i will repost with the result and the files asked 

 For @hecon5 question

Are there geographical differences between your machine and the server you're talking to? For instance, our sql server is on the other side of the country from me). Speed of light is VERY fast, but at that scale, it makes a BIG difference.
    -We don't work on internet but on local private network at a little building scale , our hardware ( Serveur/Switch) work on Gb/s 

Are you using VPN (this may impact network speed, and routing, which adds to the geographical component above).
   - No we don't use VPN / Proxy or something else

How BIG is the backend file? I've noticed with many cases the larger the backend file (used for us only during some build out testing) the larger backend files do make a difference.
    - The file contain the code weigh just around 15Mo , for accdb files the majority weigh between 5 and 20M, 50Mo for the weighty

Turn on "[Show Detailed Output](https://github.com/joyfullservice/msaccess-vcs-integration/wiki/Options#general-tab)" When building, I've noticed this updates the screen more often (once each table), so you can see progress, and helps to ensure it's still going vs truly crashed.
     - the VCS screen are freeze during the build , but the test is in progress , i will see if i have more detail on a final screen 

I hope i'm the more clear of possible 
Thanks to you for your helpers

**Comment by Keurdis** [comment]
Hello,
I come with some new, i've tried to reproduce the bug like you say.
I've created a empty database ,I've added more and more table link and try to export / build before each addition , for this step , everything work.
After that, I added the two tables that we save in XML, and it works too.
I told myself "if the problem don't come from table link , is come surely from the .accdb hosting the program "
So i create a empty database and i launch the build and it's worked, but he dost change the file that i have create , VCS create a new file itself and modified this one (the result is the same but i prefer warn).
I've tried this multiple time and after a moment the bug come again. 
I've restarted the previous step and when i'm back on the real database, that work again (i really can't explain this), then i took the opportunity to advance in my work. 

So if somebody else have the same issue try to build with a empty database, that've work for me. It's not a perfect solution but it's better than nothing meanwhile to find a real fix 
I will try to do more test the next week and send you a database afflicted by the bug 

Thanks for your helping

**Comment by hecon5** [comment]
So, it sounds like perhaps your original database may have been corrupted, if I understand correctly?

1. Building from a blank database "resets" the issue, and it begins to function "normally" again
2. will intermittently build a possibly corrupted file which when you attempt to build from source again will hang. 
3. Rebuilding from a blank file again and you're good for a bit. 

I have noticed some odd times lately when VCS throws a bizzare error prior to export. Stopping code execution and retrying seems to be the fix, and because it doesn't take but half a second, I chalk it up to likely relative to whatever hairbrained thing I am coding and testing at the moment. 

I am curious if building is experiencing similar issues, but they're quieted because it's also doing heavy lifting. I'll see if I can track that down a bit more and post some more details.

**Comment by joyfullservice** [comment]
@Keurdis - You might try a "Decompile" operation on the database. In my experience I have seen this fix problems in some of my databases. You can find [more details online for the decompile option](http://www.fmsinc.com/microsoftaccess/performance/Decompile.asp), including a tip on how to create a shortcut. 

Additional explanation can be found here: https://www.devhut.net/ms-access-decompile-a-database/

**Comment by hecon5** [comment]
@Keurdis: did you get going alright? if so, can we close this?

**Comment by Keurdis** [comment]
We don't meet the bug again , if he come again i will try the décompile solution so for this moment yes we can close the subjet , thanks for your help ! and sorry for the delayed replies !

**Comment by joshbooker** [comment]
Old thread, but for what is worth , I found build hangs on importing tables when we have a linked table with an old non-existent path.  No error and it hangs indefinitely with high cpu.  I was able to delete the tabldef files(s) and remove from the index file and the build worked rather fast as expected.  

It'd be nice if the error was handled gracefully.  "UNABLE TO LINK TABLE BLAH. PATH NOT FOUND"  Continue?

Thanks for this tool.  wish I knew about it years ago.  keep up the great work!
