### ISSUE TITLE
Run Time Error 3284

### ISSUE THREAD

**Issue by kocivan** [joyfullservice/msaccess-vcs-integration#31]
Hi, @joyfullservice 
No error when exporting files, but error while building.
![2020-05-26 (1)](https://user-images.githubusercontent.com/65854444/82846247-9194a900-9ef0-11ea-81f1-e72f12a241f6.png)

**Comment by joyfullservice** [comment]
Thank you for the screenshot. Are you able to tell me which line the error is on?

**Comment by A9G-Data-Droid** [comment]
@kocivan Try it again with the latest version. If it happens again then we do need to know where the error occurs.

**Comment by kocivan** [comment]
Hi,
Sorry for not being able to reply for a long time.
The error line is "dbs.Relations.Append rel". It gives an error while adding relationships.
I also add the application.
[TARLA3_Backup.zip](https://github.com/joyfullservice/msaccess-vcs-integration/files/4865971/TARLA3_Backup.zip)

**Comment by joyfullservice** [comment]
@kocivan - Thanks for including the sample file. I was able to reproduce the issue. It looks like adding the relationship would create a duplicate index. This is a problem with the add-in, but it shouldn't be too difficult to fix. 😄 

_Note for the programmers:_ A prior version of the code used the following to remove any existing relationships. We probably just need to bring this functionality into the new function:

    ' Remove conflicting Index entries because adding the relation creates new indexes causing "Error 3284 Index already exists"
    On Error Resume Next
    With thisDb
        .Relations.Delete newRelation.Name  ' Avoid 3012 Relationship already exists
        .TableDefs(newRelation.Table).Indexes.Delete newRelation.Name
        .TableDefs(newRelation.ForeignTable).Indexes.Delete newRelation.Name
    End With

**Comment by joyfullservice** [comment]
This issue has been fixed in version 3.1.51. Let me know if you encounter further problems!

I should also mention that while all the relationships themselves will be imported, the **_layout_** of the relationship window is not currently saved or restored. Stephen Lebans has a [free tool](http://www.lebans.com/saverelationshipview.htm) that can back up and restore the layout of the tables in the relationships window, if that is important for you. (If there is sufficient interest, we might eventually incorporate something like that into this project as well.)
