### ISSUE TITLE
Printernames longer than 32 Chars are exported wrong

### ISSUE THREAD

**Issue by Tanarri** [joyfullservice/msaccess-vcs-integration#313]
Hi,

in my System I have installed a printer, which is shared from a windowsserver 2016. The printername in my windows 10 is "Godex_VersandB_gross" on "W2K16SERVER"
![grafik](https://user-images.githubusercontent.com/6181166/160842564-4f456dc2-cc2c-43f6-99d8-d2e3841d28cf.png)

On exporting a report of my access 2013 project the printername exported as "\\\\W2K16SERVER\\Godex_VersandB_gro192.168.0.236" in the <reportname>.json

Full JSON
```
{
  "Info": {
    "Class": "clsDbReport",
    "Description": "rpt_etikett_neutral_100x150 Print Settings"
  },
  "Items": {
    "Device": {
      "DriverName": "winspool",
      "DeviceName": "\\\\W2K16SERVER\\Godex_VersandB_gro192.168.0.236",
      "Port": "192.168.0.236",
      "Default": false
    },
    "Printer": {
      "Orientation": "Landscape",
      "PaperSize": 259
    },
    "Margins": {
      "LeftMargin": 0.0396,
      "TopMargin": 0.1667,
      "RightMargin": 0.0396,
      "BotMargin": 0.1667,
      "DataOnly": false,
      "Width": 5.8271,
      "Height": 3.5521,
      "DefaultSize": true,
      "Columns": 1,
      "ColumnSpacing": 0,
      "RowSpacing": 0,
      "ItemLayout": "Horizontal Columns",
      "FastPrint": 1,
      "Datasheet": 0
    }
  }
}
```

The Printername is truncated after 32 Bytes because the structure "clsDevMode,tDevMode" has only place for 32 Bytes.
```
Private Type tDevMode
    strDeviceName(1 To 32) As Byte
    intSpecVersion As Integer
    intDriverVersion As Integer
    intSize As Integer
```

The limit of 31 Characters (plus terminating NULL) is a problem accoring to:
https://forum.powerbasic.com/forum/user-to-user-discussions/powerbasic-for-windows/14703-printer-names-longer-than-31-characters

To get a list with the complete printernames here is a example:
https://forum.powerbasic.com/forum/user-to-user-discussions/source-code/25008-demo-initialize-printdlg-for-named-printer?t=24359

But: How to do the match beetween the trucated printername and the complete printername?
Any suggestions?

PS: The "Build from source" of the project with the truncated incorrect printername could not be done without user interaction. Access is asking for the correct printer, because "\\\\W2K16SERVER\\Godex_VersandB_gro192.168.0.236" isn't found on my system.

Greetings
Tanarri

**Comment by joyfullservice** [comment]
Just to clarify this a little further, we are dealing with two different WinAPI structures in `clsDevMode`. The `DevMode` structure handles most of the printer settings, but truncates the printer name to 32 characters. The `DevNames` structure does not suffer from the 32 character limit, and includes the entire printer device name. The export process reads the printer name from the non-truncated `DevNames` data, and that is what is written to the printer settings json file.

The reason we were seeing a problem on build is that I was (inadvertently) truncating the printer name when loading it back into the `DevNames` structure. This in turn is loaded into the report export file just before it is imported into the database. Since the name was partially missing, it could not automatically map to the desired printer when the report was opened. Since the printer name was broken, this would then affect subsequent exports.

**Comment by joyfullservice** [comment]
@Tanarri - You can either hot-fix your version, or build the `master` branch from source. Let me know if this resolves the problem with your project. (Note that you will need to fix the printer name in the report, save it, then export source to ensure that the printer settings .json file has the full printer name before building from source.)

**Comment by Tanarri** [comment]
@joyfullservice 
I have build the `master` branch and the problem is resolved
Thanks for your fast help!
