### ISSUE TITLE
Reading `CurrentProject.Connection` crashes on my Access 2019

### ISSUE THREAD

**Issue by kenjiuno** [joyfullservice/msaccess-vcs-integration#316]
Hi, thanks for providing great add-in!
I want to see this add-in workable on Access 2019 (64-bit)

I'm trying to use on:
- OS: Windows 10 21H2 (64-bit) Japanese Edition
- Access: Microsoft Access 2019 (64-bit)
- VCS add-in: v3.4.20

My steps:
- Open `Version Control.accda` → no problem
- [`Install Add-In` prompt](https://user-images.githubusercontent.com/5955540/162370790-0dbe67a7-f3d8-428b-afb7-b96e58202544.png) appears → no problem
- Click button, and then I see [Success!](https://user-images.githubusercontent.com/5955540/162370872-15d12c9e-367a-4186-a4c6-c36edcbf477b.png) prompt → no problem
- Click OK, and then Access restarts, and then [Installation Complete!](https://user-images.githubusercontent.com/5955540/162370949-19e046f6-d7d0-4055-9291-b40d184deab0.png) prompts → no problem
- Access quits.
- Open a certain accdb.
- Open `Addin` → click one of `VCS Options`/`VCS Open`/`VCS Export All Source`, and then [Access crashes](https://user-images.githubusercontent.com/5955540/162371128-78ad50e8-6e4f-4226-bf6d-efc3f2964707.png)

I debugged add-in.

It seems that reading from `CurrentProject.Connection` immediately leads to crash.

![2022-04-08_14h37_20](https://user-images.githubusercontent.com/5955540/162371492-962cf77b-4c8e-46be-ad37-16d842ee27fd.png)

Alternatively reading from `CurrentProject.IsConnected` seems to be safe (no crashing) for now.

This behavior is not related with add-in. Probably this is Access's problem.

As a workaround I have replaced `CurrentProject.Connection Is Nothing` with `Not CurrentProject.IsConnected` wherever it can be applicabled.
And this workaround seems to work on my environment.

This problem is specific to me? Otherwise anyone having this kind of problem too?

**Comment by hecon5** [comment]
I wonder if it has something to do with your character mapping. 

If you can't `Debug.Print CurrentProject.Connection` or `?CurrentProject.Connection` (causes Access crash) in the immediate window, I'm suspecting it's Access's problem and has something to do with the character set / language interpretation.

### Would you try an experiment? 
1. Change your machine's in-use language to English (or any other language using the Latin Alphabet you're comfortable in, the goal is to test and see if the specific language character set is at fault).
2. Restart your machine (this will hopefully flush out any lingering language processes).
3. Restart Access (in the AddIn or just open a new database as you did above).
4. Attempt to read the connection.
5. Report results.

**Comment by kenjiuno** [comment]
Hi, thanks for reply!

I have tried to apply some English settings, however it doesn't help for now. For now I have no good idea to improve this situation, sorry:

- Changing display language to English, and then logged off.
- Changing system locale to English, and then restart Windows.

![access](https://user-images.githubusercontent.com/5955540/162456025-80b06bde-4e78-47f9-9d1e-6ce4dcd5c67b.gif)

I agree that this problem comes from Access's problem (this is not addin problem).

![2022-04-08_23h21_46](https://user-images.githubusercontent.com/5955540/162455243-4846e374-3ee1-4d13-b2ef-89dff107b9ca.png)

![2022-04-08_23h22_16](https://user-images.githubusercontent.com/5955540/162455248-6b54ab4d-3f9b-4bff-86ed-44bd02696e37.png)

![2022-04-08_23h22_28](https://user-images.githubusercontent.com/5955540/162455253-e5b68748-76eb-4f34-8e0e-d9796940b7af.png)

![2022-04-08_23h25_06](https://user-images.githubusercontent.com/5955540/162455786-a4714604-b5bc-4088-9f3a-494db00804bc.png)

**Comment by hecon5** [comment]
I see above that Access IDE is still showing Kanji when this happens; it's making me suspect it refuses to change, and that the language interpenetration is at fault here. After you change language settings, does Access still show in Japanese? If so, I'm flummoxed as to why, and also how to change it.

**Comment by kenjiuno** [comment]
> I see above that Access IDE is still showing Kanji when this happens; it's making me suspect it refuses to change, and that the language interpenetration is at fault here. After you change language settings, does Access still show in Japanese? If so, I'm flummoxed as to why, and also how to change it.

Yes, Access continuously displays Japanese on English locale/display language.

Technically it is possible to display Japanese characters upon English system locale and English display language environment.
Using Unicode version of Windows API will help it. For example, [TextOutW](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-textoutw).


The main reason of displaying Japanese texts in Access is that I have installed Japanese version of Microsoft Access.
It is possible that Access setup deployed only Japanese text assets to Windows (English text asset is missing).

**Comment by joyfullservice** [comment]
@kenjiuno - Thanks for reporting this! The `CurrentProject.Connection` is actually an object, so it wouldn't normally print anything to the debug window. It is also a remnant from the ADP project support that was discontinued after Access 2010.

The references to this object has been removed in the `dev` branch, so it won't create any problems in version 4 and beyond. (Unless you are actually exporting from an ADP project, which would not be the case in any version after 2010)

To fix this in version 3.4.20, you will want to remove the references to this object since it is not relevant to your version of Access. I believe this will fix the issue for you, and avoid the crash that you are experiencing.

Here is how you can fix it:

- Close all open instances of Microsoft Access
- Extract version 3.4.20 from the downloaded zip file
- Open the extracted file, but do not install it yet.
- Go to the VBA source code, and do a project-level find-and-replace to replace `And CurrentProject.Connection Is Nothing` with `` as shown in the following screenshot:

![image](https://user-images.githubusercontent.com/7254992/162479301-5bd8c615-9eaa-4af0-b5ca-7d29d001cfcb.png)

(There should be four occurrences replaced.)

- Compile and save the project, then close the database
- Open the database again, and this time click the button to install it.

Following the above steps should allow you to hot-fix your copy of the add-in. That is one thing that I really like about having this add-in in this format. It makes it easy to adjust the source code and reinstall it on your system.

Let me know if you have any problems after making this change.  👍

**Comment by hecon5** [comment]
Interestingly enough: [CurrentProject.Connection property (Access)](https://docs.microsoft.com/en-us/office/vba/api/access.currentproject.connection) (updated Jan 2021) says that it's still an active component. Instead of an ADP connection, it now returns the Active X (ADODB) connection. We still use it in some of our databases (all 365 or Access 19), so it definitely works.

The default member of `CurrentProject.Connection` is `ConnectionString`, which I think is the crux of the issue, or a symptom. I can't tell. But I think the issue is due to something with language and Access installation.
![image](https://user-images.githubusercontent.com/54177882/162493202-c8c20399-05a0-495a-8fa4-75d1303f80c6.png)

I also found a page on [FMS](https://www.fmsinc.com/microsoftaccess/errors/class_not_registered/index.htm) which points to this same symptom (Can't access `CurrentProject.Connection`). 

Then there's this OLD SO Thread: [Why do VBA CurrentProject.Connection statements cause all my access databases to crash?](https://stackoverflow.com/questions/10229377/why-do-vba-currentproject-connection-statements-cause-all-my-access-databases-to) which makes me think even more so that the install is borked, or has something to do with a missing language pack.

Removing the reference in the Addin will definitely get him going for now, but I think the fact it's not there is a symptom of other issues to be found later.

**Comment by joyfullservice** [comment]
Thanks @hecon5! Those are some helpful links.

**Comment by kenjiuno** [comment]
Hi @joyfullservice
Thanks, I could apply workaround (removing `And CurrentProject.Connection Is Nothing`) successfully, and now I could export database structure to filesystem I was going to do!  This VCS addin will help so much, thanks again!

ps. here is an unrelated topic, sorry if you might know that: pressing <kbd>SHIFT</kbd> key before opening Access will skip `AutoExec` macro.
[Bypass startup options when you open a database](https://support.microsoft.com/en-us/office/bypass-startup-options-when-you-open-a-database-ba66917a-68b6-4fe6-8c23-33042953a5f9)
