### ISSUE TITLE
Build from source fails with runtime error '-316276240' - Cannot set HelpContextID

### ISSUE THREAD

**Issue by cenx1** [joyfullservice/msaccess-vcs-integration#32]
### Systeminfo

- __Access version:__ MS Office 365 x64 bit
- __msaccess-vcs-integration version:__ 3.1.8

### Details

When I try to build my project from source an error is raised when trying to set the HelpContextId of the VBE Project (in the __clsDbVbeProject__ module):

![image](https://user-images.githubusercontent.com/5476302/82869264-3da8b500-9f2e-11ea-81c2-c7690f7aa62f.png)

Removing the __HelpContextId__ assignment statement makes the build move further, but I don't know what consequences it has to not set the __HelpContextId__?

The __vbe-project.json__ file contains the following:
```json
{
  "Info": {
    "Class": "clsDbVbeProject",
    "Description": "VBE Project",
    "VCS Version": "3.1.8"
  },
  "Items": {
    "Name": "Database",
    "Description": "",
    "FileName": "rel:testdb.accdb",
    "HelpContextId": 0,
    "HelpFile": "279249358",
    "Mode": 0,
    "Protection": 0,
    "Type": 100
  }
}

```

Let me know if you need further details.

**Comment by joyfullservice** [comment]
Are you using a [custom help file](https://support.office.com/en-us/article/helpcontextid-property-b0f804b2-22cb-41b8-a924-11b6fbfcc00d) in your application? The `HelpFile` and `HelpContextId` should both be read-write strings.

What happens if you try to set the property from the immediate window? Are you able to set the `HelpFile` property? I am not seeing any error in my system when setting these properties, so I am curious to see what might be causing the error.

**Comment by A9G-Data-Droid** [comment]
Something funky is going on here. In a recent export I am seeing this:

`"HelpFile": "㜸㠳〰㈱"`

And that is certainly not any help file I have ever used.

**Comment by A9G-Data-Droid** [comment]
So I found in my testing that when I was getting those automation errors setting the HelpContextId that the ID was still changing. So I added code that ignores the error and then checks to see if the value is correct. Only if the value didn't change will it throw the error.
