### ISSUE TITLE
Error import attachment field

### ISSUE THREAD

**Issue by meuslaur** [joyfullservice/msaccess-vcs-integration#329]
I come back to the subject of the fields attachment, if it can help you

I receive an error when importing a table that contains an attachment field.

The tabledef (`T_Info.sql`) file create by VCS (and export in XML format) :

`CREATE TABLE [T_Info] (
  [ID_Info] VARCHAR (15) CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [InfoTitre] VARCHAR (100),
  [InfoTexte] LONGTEXT ,
  [ID_Lang] LONG ,
  [pjCode] VARCHAR `

[![Table](https://i.imgur.com/Zk54Wyk.png "test")

The `pjCode` field is declared in `VARCHAR` (type 18)

The error occurs in the following code :

```
Private Sub IDbComponent_Import(strFile As String)

....
                Else
                    Application.ImportXML strFile, acAppendData  <--- ERROR trigger on this line
                End If
.....
```

The field is too small to receive this value

The `pjCode` field is not declared `dbAttachment` (Type 101)

The table is not recreated in the import database and in the source database

**Comment by joyfullservice** [comment]
@meuslaur - You may be encountering an internal limitation in the ability of Microsoft Access to import an attachment field from XML. This type of field is actually an embedded recordset, so the ability to import from XML depends on just how completely Microsoft implemented this capability. In my experience I have seen some limitations.

I don't know the full context of what you are wanting to do here, but if this data is important for you to add to your database during the build process, I would recommend creating your own function in VBA code to load the data. Once the function is doing what you want, then use the *Run Sub After Build* option to have the add-in call your function after building the database from source.

![image](https://user-images.githubusercontent.com/7254992/168312365-6e04a4f7-ab74-4828-a51d-5afb9a08f080.png)

For further reading, you might check out [this question](https://stackoverflow.com/questions/63421364/how-to-work-with-access-attachment-field-from-windows-forms) on StackOverflow.

Hope that helps!

**Comment by hecon5** [comment]
#209 may be of interest as well.

**Comment by meuslaur** [comment]
Thank you for your answers, and for your work.

These attachments contain code files. I use it to insert code into my little utility [Tri sur colonnes](https://github.com/meuslaur/MsAccess-Sord-Column)

I will look at your solution.

For the moment I have modified the field in long string,It's less convenient for code changes.

(N.B : Sorry for my engish)

**Comment by joyfullservice** [comment]
Thanks for sharing the link. It helps me understand more about what you are wanting to do.

Here are two ideas you might consider for storing the code, instead of using the attachment field:

You could store the code in another module, and read the procedure lines using VBE right from VBA. This would allow you to easily edit the code right in the VBA editor. The module would be a template that you would extract the VBA code from when building the continuous form. This is what I would personally recommend, based on what I am seeing in your project.

Another idea would be to store the code in a text file in the same folder as the database. It is pretty easy to read a text file from VBA using the `FileSystemObject`.

I hope that helps!

**Comment by meuslaur** [comment]
My first idea was to store the code in a module, I wanted to test the insertion in a table, I liked this idea ...

Merci encore pour vos réponses hecon5 et joyfullservice
