### ISSUE TITLE
Files with tab-separated table data should have .tsv extension

### ISSUE THREAD

**Issue by grv87** [joyfullservice/msaccess-vcs-integration#335]
It's kind of standard, isn't it?

**Comment by hecon5** [comment]
Interesting...honestly, I rarely see a Tab delimited file with `.TSV` or `.tab`. 99% of the tab delimited files I see are `.txt`. The remaining 1% are `.text`. According to [Wikipedia Tab Separated](https://en.wikipedia.org/wiki/Tab-separated_values), `.tsv` is "kinda" correct... see also [this SO SuperUser Post](https://superuser.com/questions/577875/what-file-extension-does-a-tab-delimited-file-have) for more info (TL/DR: use of `.txt` is very common).

Considering the tab exporting routine is 'custom', you may end up with [Delimiter collision](https://en.wikipedia.org/wiki/Delimiter#Delimiter_collision). It also might (probably is not) compatible if you were to take the generated tab separated file and import it with a different parser due to a variety of issues. You'd likely get data loss because this tool chose to export one way and the other chose to parse a different way (most notably with special character / tab escaping).

Lastly, the export tool is largely meant to make the table export kinda human readable for version control, not to save data elsewhere. If you want a better import/export reliability, use[ `XML`  export instead](https://github.com/joyfullservice/msaccess-vcs-integration/wiki/Options#table-data).

**Comment by joyfullservice** [comment]
Thanks @hecon5, for posting the link to the SuperUser discussion on this. Another pretty significant benefit to the `.txt` extension is that the file can be opened on virtually any computer without having to configure a custom file extension mapping. From a usability perspective, I think there is a real benefit for a new user being able to navigate to that folder, double-click the file, and see the content.

In the purist sense, the `.tsv` might be the most "technically correct" extension, but due to the lack of wide-scale adoption and the fact that this will not open by default in a text editor, I think our purposes are best served for this add-in by staying with the more common `.txt` extension.

Thanks again for the suggestion, and we can always reopen this later if there is further interest from other developers.

**Comment by grv87** [comment]
* Why this file should be opened in a text editor? It should be opened as a spreadsheet
* Some syntax highlighters detect `*.tsv` extension. For example, there is Rainbow CSV plugin for several IDEs, including [JetBrains IDEA](https://plugins.jetbrains.com/plugin/12896-rainbow-csv) and [Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=mechatroner.rainbow-csv)
* If a file has `*.tsv` extension, it can be automatically linted in CI/CD
* Some teams and enterprises have standards which file extensions could be used in VCS

@hecon5, what issues with the parser are you talking about?
Are there some known issues/incompatibilities, or it's just the supposition?

How about adding an option?

**Comment by grv87** [comment]
> (generally), you should not be exporting many tables into your repository

On the one hand, I agree. Only tables pre-filled by developers should be exported.
On the other hand, if I ever wanted to have a separate test DB, I'd keep all test data in the VCS.

If my data would ever contain any characters that should be escaped, I'd actually prefer current `FormatStringForTDF`'s escaping. This format can be read by any tool that supports TSV (formatters, linters). Even if a tool doesn't understand escaping, it won't complain about incorrect file format. While Excel's implementation requires special support.

> Viewing the TSV as a text file did what I needed to

And what about other people?
Assigning a text editor to open `*.tsv` files is much easier than opening `*.txt` files twice. First, a user opens it in a text editor (viewer). Then he figures out that it's actually a TSV file, closes it and reopens it in another app.

> I now (exclusively) use XML

Then why do you care? What's your interest in `*.txt` over `*.tsv`?
