### ISSUE TITLE
Export all objects - error 3048 - Too many databases

### ISSUE THREAD

**Issue by dfin98** [joyfullservice/msaccess-vcs-integration#338]
When I try exporting all objects for a large database, I get error 3048 - too many databases.  This happens in function IDbComponent_GetAllFromDB (on the line Set dbs = CurrentDb).

**Comment by dfin98** [comment]
It is similar, but I don't think this Access bug is the cause, as this is happening both for Access 2013 and Access for Office 365.  It also seems that this was fixed in Version 2201 of Access, but I'm on 2205.

**Comment by joyfullservice** [comment]
Are you able to determine which type of component is triggering the error? (Such as the class name where the referenced code is found.)

Also, you mention it being a large database... How many of the affected component type exist in the database? Is it something that could be replicated in a sample database to reproduce the issue?

**Comment by dfin98** [comment]
It doesn't seem to be related to a particular type of object.  At first it was happening while exporting queries.  I then did some cleanup and removed a bunch of unused queries and it got past the queries and didn't produce the error until it got to the modules.  It seems like it's more dependent on the number of objects.

Unfortunately, it would be difficult for me to produce a sample database for this.

**Comment by dfin98** [comment]
Here are the counts:
Tables: 371
Queries: 449
Forms: 221
Reports: 199
Macros: 4
Modules: 110

I've tried a compact/repair, decompile and importing all objects into a new mdb, but that didn't help.

I tried using this utility form that can determine the number of database connections that are available and found that before running the export there were 253 connections available, but when it crashed, it was down to 2 available.

http://accessblog.net/2014/04/how-many-database-connections-are-still.html

This page has some info on what causes this error:
http://accessblog.net/2012/06/one-more-source-for-cant-open-any-more.html

One other thing I tried was to import all the tables a second time, so there were many more tables in the database.  I then tried exporting all the objects again - this time it still failed when exporting the queries, but but at an earlier point.  This seems to indicate that it's related to the number of objects.

**Comment by joyfullservice** [comment]
Thanks for the additional feedback, and the helpful links! Object counts like what you posted are certainly reasonable numbers that this add-in should be able to support. I think you are probably right that the add-in is creating too many persistent references to the CurrentDB during the course of an export, and running out of connections.

I think what I probably need to do is refactor the usage of `CurrentDB` so that the objects are sharing the same connection instead of creating a new one for each object. The one drawback I have seen is that new objects created _after_ getting an instance of the `CurrentDB` object are not visible in the object collections. It's not a showstopper issue, just something I need to consider during an export, but especially during the build process.

Thanks again for bringing this to my attention! Due to the complexity involved, I will probably make this update in the 4.x version, which is currently under development on the `dev` branch.

**Comment by joyfullservice** [comment]
I did some more testing this morning, and I am still unable to reproduce the issue... I created a test database with a thousand tables and a thousand queries, and it exports with no errors on Access 2010. I tested it with the latest release of the add-in, as well as the dev version.

Do you still get the error when doing an export on the attached sample database? (Note that this may take a long time to run, depending on your system. I recommend doing it on a local SSD drive.)
[Thousand Queries.zip](https://github.com/joyfullservice/msaccess-vcs-integration/files/8863043/Thousand.Queries.zip)

**Comment by hecon5** [comment]
> I think what I probably need to do is refactor the usage of CurrentDB so that the objects are sharing the same connection instead of creating a new one for each object.

This should not be necessary... `CurrentDb` [already IS a wrapper to ensure the same object is used.](https://sourcedaddy.com/ms-access/the-currentdb-function.html)

However, given particulars and use case, it may be beneficial to cache the `Connection` Property. We do this to great effect, and it has some other nice side effects as well.

If you do want to refactor, here's what we do.

This sits in a standard module, and wraps the local connection (and a whole bunch of other items we use to talk to the front/back end with the same class).
```VBA
' This sits in a standard module, and wraps the local connection (and a whole bunch of other items we use to talk to the front/back end with the same class).
' Private variable.
' Holds the database info; makes much easier to handle.
Private m_DatabaseInfo As clsDatabaseInfo

' Wrapper function  (renamed for VCS Context)
Public Function VCSDB() As clsDatabaseInfo
    If m_DatabaseInfo Is Nothing Then Set m_DatabaseInfo = New clsDatabaseInfo
    Set VCSDB = m_DatabaseInfo
End Function
```

This is an example class module (We call `clsDatabaseInfo` because naming is lazy).
```VBA
Option Compare Database
Option Explicit

Private Const ModuleName As String = "clsDatabaseInfo"

Private m_CurrentDb As Database ' Cached "CurrentDb" pointer, however see above where it's not required; this is an example only if you did want to cache it.

Private m_ADOConnectionLocal As ADODB.Connection
Private m_ADOConnectionRemote As ADODB.Connection ' You won't use this in VCS most likely, but it's here as an example

Private m_AccessVersion As Long ' Example property we use a fair bit for error detection and handling per version.

Private Sub Class_Initialize()
    On Error Resume Next
    Perf.OperationStart ModuleName & ".Initialize"
    ' Any special handling (we grab Access Version, and some other details, omitted for brevity).
    Perf.OperationEnd
End Sub

Private Sub Class_Terminate()
    On Error Resume Next
    Perf.OperationStart ModuleName & ".Terminate"
    m_ADOConnectionRemote.Close ' This is not generated during Initialize, only at first use of remote but we do need to close it.
    Set m_ADOConnectionRemote = Nothing
    Perf.OperationEnd
End Sub

' Lots of other functions and properties about this particular front end (version details, build dates, etc.) we don't use often but are very handy.

Public Function CurrentDbCache() As Database
    If m_CurrentDb Is Nothing Then Set m_CurrentDb = CurrentDb
    Set CurrentDbCache = m_CurrentDb
End Function

Public Function GetFrontEndConnectionADO() As ADODB.Connection
    Perf.OperationStart ModuleName & ".GetFrontEndConnectionADO"
    
    If m_ADOConnectionLocal Is Nothing Then
        Perf.OperationStart ModuleName & ".GetFrontEndConnectionADO.Create"
        Set m_ADOConnectionLocal = New ADODB.Connection
        Set m_ADOConnectionLocal = CurrentProject.Connection ' Or CurrentDB.Connection, depending on what your goal is here
        Perf.OperationEnd
    End If
    
    Set m_ADOConnectionLocal = m_ADOConnectionLocal
    Perf.OperationEnd
End Function

```

You'd then call it like this: `VCSDB.GetFrontEndConnectionADO` or VCSDB.CurrentDbCache`. Fairly minimal refactoring required. and you can add functionality as you see fit...and IntelliType will help you, which is a super nice addition if you have scatterbrain like me and can't remember what you called various functions.

**Comment by hecon5** [comment]
I ran the thousand query / table export; I did get an "unhandled error", but it exported just fine. 

[Export.log](https://github.com/joyfullservice/msaccess-vcs-integration/files/8863508/Export.log)

![image](https://user-images.githubusercontent.com/54177882/172670674-04edf8e7-54a6-4717-8392-4cbaa474cc14.png)

**Comment by joyfullservice** [comment]
In another test, I exported 983 linked tables (SQL Server) with no issue... Let us know what you find out!

**Comment by dfin98** [comment]
Testing further I found that the problem seems to be happening for a complicated query where the source is another query (which is based upon a another query).  I also had the problem occur with a query that was based on a union query.

I also tried exporting a different database with over 1800 objects and it worked fine.

I think I need to explore the problem with the complicated queries further.  This is a legacy database where a lot of the queries were multi step operations.  Maybe I just need to simplify the queries that are causing the problem and the export will work.

**Comment by joyfullservice** [comment]
It sounds like this is a pretty unique situation... In my own testing I am not finding excessive use of database connections during normal export/import operations. I would propose that we go ahead and close this issue unless we are able to pinpoint a specific addressable issue.
