### ISSUE TITLE
VCS 3.4.22: ERROR: Unhandled error found before `On Error` directive

### ISSUE THREAD

**Issue by alanv73** [joyfullservice/msaccess-vcs-integration#341]
![vcs_error](https://user-images.githubusercontent.com/29257817/178546751-09503504-ae3a-4f84-8cf0-6cd6c7582724.png)

[Export.log](https://github.com/joyfullservice/msaccess-vcs-integration/files/9095161/Export.log)

**Comment by alanv73** [comment]
Here goes...
The error:
![vcs_error1](https://user-images.githubusercontent.com/29257817/178582563-d0ce5023-5ea5-437f-8e87-4c5977c92fd5.png)

The debug point:
![vcs_error2](https://user-images.githubusercontent.com/29257817/178582644-25e2b75e-d5f3-49fd-adc5-ae03418df4a7.png)

If I step through the code I get to here:
![vcs_error3](https://user-images.githubusercontent.com/29257817/178582687-26e3cb71-755c-4457-b252-f9e8a4f34d2b.png)

**Comment by joyfullservice** [comment]
Thanks for the additional information! I did some testing with the same version of the add-in and I am not seeing this behavior on my system... Which version and build of Access are you currently running?

Also, you might try renaming the source folder to see if the export runs correctly on a fresh export with no existing files. (Noting that the call stack in your screenshot points to something connected with clearing orphaned source folders.)

Have you been running version 3.4.22 for a while, and this suddenly started happening, or did you recently upgrade from an older version of the add-in?

**Comment by alanv73** [comment]
In a troubleshooting attempt I rebuilt one of my databases from source. It's choking on the theme file.

![image](https://user-images.githubusercontent.com/29257817/178761852-2b8143b9-74b0-4630-8772-71f6cb25f457.png)

[Build.log](https://github.com/joyfullservice/msaccess-vcs-integration/files/9103274/Build.log)

**Comment by joyfullservice** [comment]
It sounds like you are the right track there... It is a little challenging to troubleshoot without being able to reproduce the problem on my end, but that is what I love about having this add-in running as an unlocked Microsoft Access VBA project. You can literally debug the add-in itself, just as you would your own project.

After opening the add-in the first time in the current instance of Microsoft Access, it will be loaded as a VBA project. You can then add break points to the code, view locals and the call stack, and even edit and continue just like you would in your own database. The key difference is that none of your changes to the add-in will be saved, since it is loaded as a library, not as the current database. (To reset the add-in to its original condition, simply close the Access instance and open it back up.)

I would suggest adding some break points in relevant places, such as where the add-in begins the export of the theme and shared images. F8 and Shift+F8 are helpful keyboard shortcuts to step through the relevant code. While the code is paused, you can hover over variables or print to the immediate window to get a better understanding of what is happening.

As you do this, hopefully it will be pretty efficient to pinpoint exactly what is causing the problem. Like you mentioned, it [could be a bug](https://www.devhut.net/category/ms-access/ms-access-bugs/) in a recent update of Access, or it might be something we could tweak in the code to resolve the issue.

Keep me posted!  😄

**Comment by Dlothcab** [comment]
Access Version: Microsoft® Access® 2016 MSO (Version 2206 Build 16.0.15330.20144) 32-bit 
Version Control System: 3.4.22

I've been running into the same problem, but it stops at this line instead (with error 13/Type mismatch):

![image](https://user-images.githubusercontent.com/104448478/178773479-1b46d7ea-7a6d-414c-ba13-d548eb479f18.png)

This is the recordset that I get by running the sql statement
![image](https://user-images.githubusercontent.com/104448478/178773897-cac6d0c8-e69f-4bd8-8b02-c76019939de3.png)

When I check to type of m_Rst!Data in the immediate window it says 101. 
![image](https://user-images.githubusercontent.com/104448478/178773694-e52557d0-eca1-4dbb-acb9-5a1ccdebcc65.png)

**Comment by Dlothcab** [comment]
![image](https://user-images.githubusercontent.com/104448478/178776711-7f8baf4c-b256-4f78-9412-8efb7ca20a2f.png)

**Comment by joyfullservice** [comment]
Wow. Sounds like a new class type... I assume this must have been introduced in a recent release.  🤔

**Comment by mwolfe02** [comment]
Yep.  See this [StackOverflow answer](https://stackoverflow.com/a/72860270/154439) from Gustav for details.

**Comment by alanv73** [comment]
I just changed all of the variable declarations of DAO.Field2 to DAO.Field3 and the errors are gone.

![image](https://user-images.githubusercontent.com/29257817/178779914-a6c3dab4-f4cf-4ce4-8c7c-f668e3fa6243.png)


![image](https://user-images.githubusercontent.com/29257817/178779800-6482f9d1-ee41-4270-a8ff-3a1ce7af2d3d.png)

**Comment by mwolfe02** [comment]
@alanv73 What if you change the declarations to `DAO.Field` instead of `DAO.Field3` (or `DAO.Field2`)?

Reading between the lines of [Gustav's answer on SO](https://stackoverflow.com/a/72860270/154439), it looks like that is the approved way to avoid future breaking changes when Microsoft inevitably introduces `DAO.Field4`, `DAO.Field5`, etc.

> When we make an update to an interface, we can’t update the existing interface, but must extend the existing interface. We are looking into whether we can improve the backward compatibility issue for cases where people explicitly declared variables to be of type Field2, rather than just Field.

**Comment by joyfullservice** [comment]
> @alanv73 What if you change the declarations to `DAO.Field` instead of `DAO.Field3` (or `DAO.Field2`)?
> 
My thought exactly! This would be helpful for backwards compatibility because `DAO.Field3` won't compile on Access 2010.

**Comment by alanv73** [comment]
That works as well.

[Export.log](https://github.com/joyfullservice/msaccess-vcs-integration/files/9104091/Export.log)

**Comment by mwolfe02** [comment]
If switching to `DAO.Field` works, I would also try switching from `DAO.Recordset2` to `DAO.Recordset`.  

I have a feeling the same theory will apply there, too.  Switching to `DAO.Recordset` now might save some future grief (assuming it works).

**Comment by joyfullservice** [comment]
Thank you all for your help testing that in the newer versions of Access! I will plan to roll out an updated release this afternoon to address the issue.

**Comment by alanv73** [comment]
> If switching to DAO.Field works, I would also try switching from DAO.Recordset2 to DAO.Recordset.

Also no errors in this test case.

[Export.log](https://github.com/joyfullservice/msaccess-vcs-integration/files/9104136/Export.log)

**Comment by mwolfe02** [comment]
Awesome!  Thanks for testing that @alanv73!  I'm writing an article about this on https://nolongerset.com.  Check back later today to see it.

**Comment by mwolfe02** [comment]
Article is live: [WARNING: Do NOT Declare DAO Fields As Field2, Field3, etc.](https://nolongerset.com/bug-alert-dao-field3/).  Thanks again, @alanv73, for your work in confirming the recommendations from Microsoft.

**Comment by joyfullservice** [comment]
Version 3.4.23 is now ready for [download](https://github.com/joyfullservice/msaccess-vcs-integration/releases). Thanks again to everyone for the help in getting this resolved!  😄

**Comment by arpm-awv** [comment]
Thanks, I got it installed. Tomorrow morning I'll set to refreshing all of my repos that were affected by the bug. I'll let you know if I have any trouble.

**Comment by alanv73** [comment]
Thanks, I got it installed. Tomorrow morning I'll set to refreshing all of my repos that were affected by the bug. I'll let you know if I have any trouble.

<wrong account used before>
