### ISSUE TITLE
Exclude export table def SQL for linked tables?

### ISSUE THREAD

**Issue by ollypsilon** [joyfullservice/msaccess-vcs-integration#386]
https://github.com/joyfullservice/msaccess-vcs-integration/blob/0ff31fe6ba208356d774ace113a67f48df4e000e/Version%20Control.accda.src/modules/clsDbTableDef.cls#L100

I wonder if for linked tables creation of table def SQL should be omitted on export or a kind of warning is created.
Because if created and option `Force import of original SQL for queries` is used created table by SQL won't be a linked table like it's originally designed.
Maybe integrate in block for non-linked tables?
https://github.com/joyfullservice/msaccess-vcs-integration/blob/0ff31fe6ba208356d774ace113a67f48df4e000e/Version%20Control.accda.src/modules/clsDbTableDef.cls#L54

I don't know a way to create a linked table by SQL so changing `SaveTableSqlDef` might not be able to do the trick.
https://github.com/joyfullservice/msaccess-vcs-integration/blob/0ff31fe6ba208356d774ace113a67f48df4e000e/Version%20Control.accda.src/modules/clsDbTableDef.cls#L199

**Comment by joyfullservice** [comment]
The main purpose for the SQL table definition is to provide a simple, high-level overview of significant changes that were made to a table object. (Such as adding a column or changing a data type). These files are simply for reference, and not used in any way during the import/build process.

Because the actual table definition files contain very granular xml content, these SQL files give a quick reference on the overall structure of a table. I suppose this might be a little confusing for new users since that works a little differently from the query SQL files, which can actually be used during the build process. (And are needed some rare situations with certain types of complex joins.)

**Comment by ollypsilon** [comment]
> The main purpose for the SQL table definition is to provide a simple, high-level overview of significant changes that were made to a table object. (Such as adding a column or changing a data type). These files are simply for reference, and not used in any way during the import/build process.

Ok, sorry, my bad. The option is used for queries, not tables 🤦 

> Because the actual table definition files contain very granular xml content, these SQL files give a quick reference on the overall structure of a table. I suppose this might be a little confusing for new users since that works a little differently from the query SQL files, which can actually be used during the build process. (And are needed some rare situations with certain types of complex joins.)
