### ISSUE TITLE
All external functions must be pointer safe for 64-bit

### ISSUE THREAD

**Issue by A9G-Data-Droid** [joyfullservice/msaccess-vcs-integration#42]
A new 32 bit external library was added, breaking 64bit support.

Every time we add a new external library call it must be pointer safe for 64-bit users.

![image](https://user-images.githubusercontent.com/26984068/83284343-654b8780-a191-11ea-8d9a-5fd2c01788f5.png)

**Comment by joyfullservice** [comment]
Sorry that got missed when merging in the other changes in #41. I am not running 64-bit so I don't get the compile errors and have to remember to specifically check that anytime I am working with APIs. Thanks for the PR to get that merged into master! I will probably add a release later this afternoon if I can so the fix is ready for install over the weekend.

Also, for what it's worth, the `PtrSafe` and `LongPtr` declares also work just fine in 32-bit Access (2010) so I think we are safe to just use a single set of APIs without the compiler directives that existed in some earlier versions of this module.

**Comment by A9G-Data-Droid** [comment]
Agreed. Those are Microsoft functions that handle the compiler directives for you. We only need to use custom compiler directives for our own code that doesn't work on all bitness. (Which is rare)
