### ISSUE TITLE
Testing database fails tests because of hard coded paths

### ISSUE THREAD

**Issue by A9G-Data-Droid** [joyfullservice/msaccess-vcs-integration#46]
The linked tables need full paths and currently they point to locations that only exist on the development box of @joyfullservice . This makes it so other developers can't use the testing DB out of the box.

To fix this we need an AutoExec function that relinks all linked objects using the current relative path to the DB.

**Comment by joyfullservice** [comment]
This works for now. Eventually I would like to support the `rel:` syntax for relative paths on the connect property of linked tables, at least for ones that we can easily parse. This would allow us to build the test database from source, and manage it that way instead of working with the binary file.
