### ISSUE TITLE
Incorrect theme in built version

### ISSUE THREAD

**Issue by cenx1** [joyfullservice/msaccess-vcs-integration#48]
### Systeminfo

Access Version: MS Office 365 64bit

msaccess-vcs-integration: 3.1.14

### Details

If I select a theme for a database, say __Integral__, and export and build the database, the active theme is incorrect.

__Steps to reproduce:__
1.  Open the _Testing_ database in this project.
1. Open __frmMain__ in _Design Mode_ and select a theme, e.g. __Integral__ and save.
1. Export the database and build from source afterwards.
1. Close the database and open it again.
1. Open __frmMain__
    * __Expected:__ The form uses the __Integral__ theme
    * __Actual:__ The form uses the __Organic__ theme or some other theme.

### Observations

* The theme in __dbs-properties.json__ is correct. upon export time.
* If the database is exported right after it is built, the theme is missing from __dbs-properties.json__
* Forms and reports (GUI parts) are altered upon selected theme and with the incorrect theme active the export are altering all GUI parts.
* __MSysResources__ table are empty after build. After closing the database the __Organic__ (or another incorrect) theme is added to the table.
* Manually adding the theme information to __MSysResources__ table after build does not have an effect. The incorrect theme is appended to the table after database is closed and seems to superseed previous rows.

I will add more info as I come upon it.

**Comment by joyfullservice** [comment]
Thanks for your work on this! The class for the theme will probably be very similar to the one for shared images (`clsDbSharedImage`). I was envisioning exporting the themes into a "themes" folder as unzipped contents with each parent folder representing a theme. At build time, the contents would be zipped and loaded into the MSysResources table.

**Comment by cenx1** [comment]
It sounds like you have a good understanding of how it works and you thoughts seem valid. I hope we can figure this out as it gives me a lot of extra work to look all the files through everytime I do an export before comitting.

But I am a little worried that changes made to the __MSysResources__ table are overridden after database is restarted. I tried with making a procedure in the project that I am exporting and added it to run after build, but it was like the changes to MSysResources did not take effect when the database was restarted.

**Comment by joyfullservice** [comment]
What happens if you load the theme and database properties before importing the forms and reports?

**Comment by joyfullservice** [comment]
Made some good progress this morning on theme support... I am now able to extract the themes from the source database and save them in unzipped format. 3f15102 Of course the real test will be what happens when we import them back into the database, but I am optimistic that we will find a way to do this.

**Comment by cenx1** [comment]
Nice job! 

What I have done until now was to create two functions, one for saving theme and one for loading:

```vb
Public Function SetTheme()
    
    Dim rsMsysResources As DAO.Recordset2
    Dim rsAttachment As DAO.Recordset2
    Dim strThemePath As String
    strThemePath = CurrentProject.Path & "\CustomTheme.thmx"
    
    Set rsMsysResources = CurrentDb.OpenRecordset("SELECT * FROM MSysResources WHERE [Type] = 'thmx'", dbOpenDynaset)
    If Not rsMsysResources.EOF Then rsMsysResources.MoveLast
            
    If Not rsMsysResources.EOF Then
        
        Debug.Print "Update " & rsMsysResources("Name")
        rsMsysResources.Edit
        Set rsAttachment = rsMsysResources("Data").Value
        If Not rsAttachment.EOF Then rsAttachment.Delete
        
    Else
        
        Debug.Print "Add new theme (CustomTheme)"
        rsMsysResources.AddNew
        rsMsysResources("Extension") = "thmx"
        rsMsysResources("Type") = "thmx"
        Set rsAttachment = rsMsysResources("Data").Value
        
    End If
    
    rsMsysResources("Name") = "CustomTheme"
    
    rsAttachment.AddNew
    Debug.Print "Load theme attachment from file '" & strThemePath & "'"
    rsAttachment("FileData").LoadFromFile strThemePath
    rsAttachment.Update
    rsMsysResources.Update
    
    rsMsysResources.Close
    
    Dim p As Property
    Dim strPropName
    Dim blnPropFound As Boolean
    blnPropFound = False
    strPropName = "Theme Resource Name"
    For Each p In CurrentDb.Properties
        If p.Name = strPropName Then
            Debug.Print "Theme Resource Name exists - update with 'CustomTheme'"
            CurrentDb.Properties("Theme Resource Name") = "CustomTheme"
            blnPropFound = True
        End If
    Next
    
    If Not blnPropFound Then
        Debug.Print strPropName & " was not found - create new property with value 'CustomTheme'"
        Set p = CurrentDb.CreateProperty(strPropName, dbText, "CustomTheme")
        CurrentDb.Properties.Append p
    End If
    
    Debug.Print "Done"
    
End Function
```

and 

```vb
Public Function SaveTheme()
    
    Dim rsAttachment As DAO.Recordset2
    Dim rsMsysResources As DAO.Recordset2
    Dim strThemePath  As String
    Dim fso As Object
    Set fso = CreateObject("Scripting.FileSystemObject")
    strThemePath = CurrentProject.Path & "\CustomTheme.thmx"
    Set rsMsysResources = CurrentDb.OpenRecordset("SELECT * FROM MSysResources WHERE [Type] = 'thmx'", dbOpenDynaset)
    If Not rsMsysResources.EOF Then rsMsysResources.MoveLast
    Set rsAttachment = rsMsysResources("Data").Value
    If fso.FileExists(strThemePath) Then fso.DeleteFile strThemePath
    Debug.Print "Save theme attachment to '" & strThemePath; "'"
    rsAttachment("FileData").SaveToFile strThemePath
    rsAttachment.Close
End Function
```

The two functions were invoked after export (SaveTheme) and after build (SetTheme).

Maybe you can use some of the code in there (I know it is rough). 😄

**Comment by cenx1** [comment]
I will take a look at what you have come up with so far. 👍

**Comment by joyfullservice** [comment]
Thanks, @cenx1! That is a helpful jump start on the import side.

**Comment by joyfullservice** [comment]
Success!!  👍  I was able to get the theme to load into the database during build! I need to polish up a few things on the coding side, but I wanted to pass on the good news.  😄  The key was I needed to import the theme before importing the objects that depend on the theme.

When the first form or report is created/imported into the database, this automatically creates the `MSysResources` table. Since you have to have the theme before you import the form, but you can't import the theme till you have a resources table, I am creating a temporary form to force the generation of the table, then loading the themes, then proceeding to load the rest of the objects and database properties. In my proof of concept, this successfully loaded and applied the theme to my form.

**Comment by joyfullservice** [comment]
@cenx1 - Could you do some testing after the latest update dc8e38c? It seems to be working for me to export and import themes. Then if you have time, it would be great if we could finish this out with a few finishing touches and enhancements:
* [ ] Remove orphaned theme folders.
* [ ] Don't import themes that are not used by any objects (scan the source files of forms and reports)
* [ ] Add option to extract themes on export. (Helpful if you are customizing themes, but does slow down the export slightly.)
* [ ] Use the nifty `.SaveToFile` function to download the theme file, rather than parsing the binary data like I was originally doing. (Simplifies the code and makes it more robust.)

Thanks for your help with this project! Hopefully my work on the theme functionality will help save you time on your end as well.  😄

**Comment by cenx1** [comment]
Nice job! 👍 I tested the latest update and can confirm that the theme is exported with the project and added upon build time. 

I do however get two themes after build. I believe the unwanted theme that was not exported is added automatically somehow during build. If I do a __compact and repair__ the unwanted theme is removed and only the desired theme is present.

Maybe the unwated theme is some kind of default for when creating the first form in a project?

**Comment by joyfullservice** [comment]
That's good to know about the unused themes being removed in a compact and repair.

Yes, I believe you are correct about the default theme being added when that first temporary form is created to trigger Access to add the `MSysResources` table.

The default theme is specified in the application options:

![2020-06-04 06_51_40-Microsoft Access](https://user-images.githubusercontent.com/7254992/83753647-4d13b680-a630-11ea-8c79-9f4f78b09e69.jpg)

Probably a simple approach here would be to delete any records in the MSysResources table immediately after it is created. Themes would then be loaded from the source files as part of the build, and you wouldn't need to worry about having themes that were not part of the export.

**Comment by cenx1** [comment]
Thanks for the information. For some reason I had the __Organic__ specified in the __Default Theme__ section you just showed.

**Comment by joyfullservice** [comment]
Thanks again, Casper, for your work on #50 I believe that fully resolves this issue, but feel free to reopen it if there are further issues with themes.
