### ISSUE TITLE
Suggestions on how to implement in build pipeline

### ISSUE THREAD

**Issue by cenx1** [joyfullservice/msaccess-vcs-integration#51]
I think this project is becoming very good and I am starting to use it in a build pipeline. I would like to ask if there are any thoughts on how this can be achieved?

I want to be able to execute a build from a GitLab Runner / Azure DevOps Agent / GitHub ... / Other commandline tools. Is it possible to invoke the __Version Control__ add-in from commandline with parameters somehow?

**Comment by joyfullservice** [comment]
Great ideas! Here are a few initial thoughts...

You could use the /x and /cmd [command line parameters](https://support.office.com/en-us/article/command-line-switches-for-microsoft-office-products-079164cd-4ef5-4178-b235-441737deb3a6#ID0EAABAAA=Access) when launching Access to run a specific procedure, such as a function to build a database from source. If you launched the add-in file, you could pass it the path of a function to run a silent build on a specified path of source files.

In the same way that we have a place to specify a sub to run after build, we could add a new option where you would specify a function name to validate the build after restarting the newly-built database. The add-in would be expecting the validation function in the new database to return `True` after a successful build. The add-in could then return this status to the pipeline.

I have done some work with GitLab pipelines, and I could see this working out very nicely on a GitLab runner on Windows box to build and validate the database automatically when a commit is pushed to the repository. On a successful build, this pipeline could roll to the next task and deploy the database for the end users.

If you are interested, I have some scripts that build a click-once installer around a Microsoft Access database application in a fully automated way. When the user opens the program, it automatically updates to the latest version if a new one has been deployed. I have been using this for several years and it has worked great in our environment.

Since this automated deployment pipeline for Microsoft Access via GitLab is a bit outside the scope of this particular project, I could see this being its own separate repository, and we would add functionality to the Version Control add-in to integrate nicely with it, but keeping the development efforts focused separately on the two integrated but independent projects.

**Comment by joyfullservice** [comment]
As to how to launch the add-in from VBA code before it has been loaded, I have not been able to find any documentation on how this can be done for a Microsoft Access add-in. That being said, I did a little testing, and the following code seems to provide the same functionality of loading the add-in project like what you see the first time you launch Version Control from the add-ins menu.

```
With References
	.AddFromFile Environ$("AppData") & "\Microsoft\AddIns\Version Control.accda"
	.Remove references("MSAccessVCS")
End With
Run "MSAccessVCS.AddInMenuItemLaunch"
```

**Comment by cenx1** [comment]
Thanks for the info. I will try it out today. 

I would be very interested in seeing what you have done and I agree that it might be out of scope for this project.

**Comment by joyfullservice** [comment]
Sounds good! Would you like to create a project called `msaccess-devops`? Then I can fork the project and upload what I have, and you can build out from there.

**Comment by cenx1** [comment]
Awsome! I have created this project as you suggested: https://github.com/cenx1/msaccess-devops

I have not had a break through on the tips you gave me yet. When I add the reference and start a build, the `SetTimer` callback does not work. I believe this is because when adding a reference instead of activating an add-in the code gets added to the `CurrentDb` and hence closed when the build is running. Does that make sense?

**Comment by joyfullservice** [comment]
Yes, I think you are probably correct that loading the temporary reference to the add-in will not persist when the `CurrentDB` is closed. Perhaps we could try a question on StackExchange and see if one of the Access experts out there knows how to invoke an add-in.

**Comment by joyfullservice** [comment]
Just an update here... I received a helpful clue today from the StackOverflow post, and it looks like we have a way to load the add-in at the application level! This means that conceptually we can now couple these processes together in a fully automated unattended runner process that builds, validates, and deploys the application automatically from the commit!

**Comment by cenx1** [comment]
Thank you very much Adam for your effort in this!

I just tested the steps and have it working now in a prototype. 😄

**Comment by joyfullservice** [comment]
@cenx1 - I have an open pull request on [cenx1/msaccess-devops](https://github.com/cenx1/msaccess-devops) with the initial code base for this project. (I believe you were able to use this to develop your prototype.) When you get a chance, it would be awesome if you were able to accept the pull request, and share some of your updates and enhancements, and perhaps also the .yaml file in your devops project. I think there are several of us that would be interested in using this in our internal environments. Through the GitHub project we can continue to collaborate and enhance the project to benefit everyone.

I will go ahead and close this issue out now, since further developments on the DevOps side will be targeting the new `msaccess-devops` project. Thanks again for your contributions to the community!!

**Comment by AlexHedley** [comment]
https://github.com/msaccess-vcs-integration/msaccess-devops
