### ISSUE TITLE
"Old" VCS code exported - should be excluded?

### ISSUE THREAD

**Issue by marshall-ucsd** [joyfullservice/msaccess-vcs-integration#57]
The @timabell source code specifically excluded `VCS_*` files from export, but those files were included in an export.
Not a bug, per se, but probably worth checking for and reporting on the presence of (potentially obsolete/unneeded) `VCS_*` files.

**Comment by joyfullservice** [comment]
You are correct that none of those files are needed anymore. Since we are running the export from an Add-in, we don't have to make any code changes to the database to export the code.

We could put some notes in the installation instructions, but not many people read those.  😄  I went ahead and added the following check at the end of the export process. It could get irritating if they keep seeing it after every export, but long term they will be better off removing the modules if they are using the add-in going forward.

![image](https://user-images.githubusercontent.com/7254992/87709032-41f09200-c769-11ea-911e-7ae45ea26bad.png)
