### ISSUE TITLE
VCS_Loader.bas is a confusing artifact of the old loading method found in Upstream

### ISSUE THREAD

**Issue by A9G-Data-Droid** [joyfullservice/msaccess-vcs-integration#6]
I also find having modVersionControl twice is not sane.

I propose that modVersionControl be removed from the main add-in and put in to something like VCS_Loader.bas that can be simply imported and ran.

**Comment by joyfullservice** [comment]
Here is the reasoning behind including `modVersionControl` in the add-in.

1.) This allows me to run the normal commands to export the source code from within the add-in itself, which makes development consistent with how I export source in all the other projects that utilize this add-in. Usually I find issues with the add-in while using it in other database projects, so bouncing back and forth between the Version Control library and the production database is a lot easier if you don't have to add and remove a code module each time you make a change to Version Control and export the changes to GitHub. (You can't even run the export command without this module, so it would be a little difficult to push changes to this GitHub project.)

2.) While it is true that a copy of the same module is in both the current database project and the add-in, the `Option Private Module` makes it so you can only run the copy that is in your **current** database, not the module that is in the add-in database. You will only ever see one function listed in the autocomplete list on the coding side. In other words, the scope of the module is private to the database where it physically exists.

3.) If an update to the add-in includes additional enhancements to this module, you can easily compare the changes to the current module and adjust as needed.

I am not necessarily opposed to pulling this out, I am just not sure how it makes it simpler to use... In the current approach, to import the module into a new database, you simply use the Access import tools (not the VBE import) and select the module from the add-in database. (The same way you would import a form or query from another database.) Importing a code module from a text file in the VBA IDE is a totally different process that an end user may or may not be familiar with.

Let me know if you still feel like it would be better to split out the module to a separate file that has to be imported into VBE before the project can be used... Certainly open to ideas, just wanting to make sure I understand.  :smile:

**Comment by A9G-Data-Droid** [comment]
1) Correct, you would only need the module there if you were working on the add-in. The goal is to not need to make changes to the main Version Control Library ever. It's a separate project and so I would separate my time of working on the library and working on my other projects. You should be able to share one version of the Version Control Library between all of your projects. When you update that one library it is then updated for all of your projects. To update the library you would have to add the module, export, and remove the module. That should only be done once at the end of working on the library. 

2) That is nice how it works. 

3) When LoadVersionControl itself needs to be updated it needs to be updated across all projects while not destroying any per-project settings. This is something that I would want to avoid doing very often for that reason. Maybe it needs an update function of it's own.

**Comment by joyfullservice** [comment]
1. Right, ideally you would not need to change things very often in the VCS library. But in my experience, you do encounter things from time to time where a database has something unique that just doesn't work quite right (i.e. #3) and changes need to be made in VCS to meet the evolving development needs. To test the changes, I need to go back to my project with the updated VCS add-in loaded, and ensure that it actually fixed the problem and didn't create new issues.

Regarding sharing the add-in between projects, I used to do that, but later moved to a deployment system that uses automated Click Once installer packages to install updates automatically on the end user's computers. The shared libraries caused problems when multiple projects (and nested libraries) referenced different versions of add-ins. I also had issues with multi-user access on the databases, so it was ultimately solved by moving to a deployment model where copies of the front-end databases were pushed out to the end users (and updated automatically). This is all done with a single line command from the debug window. Someday I hope to put that project out on GitHub as well, since I think others would probably find it helpful as well.

Perhaps a better long-term approach here would be to make the VCS library more of a true Access add-in (.accda) where it would be automatically loaded on the development machine and we don't have to worry about loading and unloading VCS within the work database. http://www.skrol29.com/us/vtools.php is a great example of this. (And a helpful tool for certain things as well.)

3. Agreed. The goal is to keep this module as simple as possible by keeping all the logic in the VCS library, and using this module strictly for loading the add-in and setting the options. Using an array for options avoids the dependency on the VCS add-in, but it is nice to outline what these options are and how to use them. However, perhaps it would be better to simplify even this, and direct the user to a web page (on GitHub) where they can see the options explained and see examples. This would allow us to continuously update the documentation without needing to include all these changes in the work databases.

**Comment by A9G-Data-Droid** [comment]
For automatic updates of front ends I use "Application Starter" http://www.peterssoftware.com/aps.htm

I have a heavily modified version for internal use. It works great. Users only ever see\use the updater which shows a splash screen while it does: backup, compact\repair, update, and then opens the local FE. Every time they open it they are getting the current version, just like click-to-run does. 

The version control add-in should not be included in the production version of FE for users so I must assume you are talking about other add-ins that you distribute to your users. I am calling `InitializeVersionControlSystem DEBUGMODE` in my autoexec so that I can automatically load or unload the VersionControl system based on if I have enabled the debug mode of my DB. (DEBUGMODE also flips all sorts of things to behave differently than production so I can test my application without it touching all the external things it touches in the real world. Emails only go to me, etc.) For Version Control, I would want to use just one version of the library for all my projects. 

So here's an idea: We could treat the .ACCDA as the "Release". Treat it like the binary that it is and don't check it in to Git at all. Then you can make GitHub Releases that only contain the two files the a user would download in a zip. This allows us to use GitHub as intended, and then you can release a new version whenever you see fit. Currently, the releases only have source code downloads. There should be the Binary release and the source code release, just like any other language. To make the binary release, you would just need to run "ImportAllSource" from the latest Master. That should replace all the modules with the source. If it doesn't then we need to fix that function.
