### ISSUE TITLE
Run-time error '2950': Reserved Error

### ISSUE THREAD

**Issue by jschof** [joyfullservice/msaccess-vcs-integration#67]
I get this when I click on the button to export.

**Fails in:** modFunctions.SaveComponentAsText 
**At Line:** Application.SaveAsText intType, strName, strTempFile
**cCategory.Category**= "table data macros"

The table it fails on has no data macros.

As a workaround I am ignoring the error in clsDbTableDataMacro but it should probably be handled more elegantly:

```
Private Sub IDbComponent_Export()
    ' Save structure in XML format
    On Error Resume Next
    SaveComponentAsText acTableDataMacro, m_Table.Name, IDbComponent_SourceFile
    On Error GoTo 0
End Sub
```

**Environment**:
Windows 10
Access for Microsoft 365
MSAccessVCS 3.1.56

**Comment by joyfullservice** [comment]
Interesting... This probably stems from the difficulty in determining whether a table actually contains table data macros. Since we don't have anything directly exposed in the object model, we are checking the (undocumented) `LvExtra` field in `MSysObjects`. See [this link](https://stackoverflow.com/questions/31755802/) and `clsDbTableDataMacro.IDbComponent_GetAllFromDB` for additional details on this approach.

Since this may not be 100% accurate, as experienced by your testing, I have added some additional error handling around the `.SaveAsText` function to gracefully ignore the false positive.

**Comment by jschof** [comment]
Yes I stumbled upon that link while debugging and can confirm that it is not 100% accurate. I couldn't find anything else hence the "hack job". Will use your code when I upgrade to the next release. Thanks!
