### ISSUE TITLE
"Build from source": VBE References issues

### ISSUE THREAD

**Issue by Indigo744** [joyfullservice/msaccess-vcs-integration#72]
Hello,

(I hope you don't mind I open all these issues... 😅 I'm very interested in this project!)

Please note: I'm using Office 2016 32-bit.

-----
**First issue : some default references are always added.**

Steps to reproduce:
1. Create an empty ACCDB file
1. Go to VBE, remove all references except the 2 built-ins
   ![image](https://user-images.githubusercontent.com/7137528/96505382-56579580-1256-11eb-90b7-189d2ef6119a.png)
1. Export as VCS
1. Build from source
1. Go to VBE, see that 2 references are added:
   ![image](https://user-images.githubusercontent.com/7137528/96505336-42ac2f00-1256-11eb-869d-48e1cf16baee.png)

-----

**Second issue : some version are not the same.**

Steps to reproduce:
1. Create an empty ACCDB file
1. Go to VBE, add reference to `Microsoft Office 16 Object Library`
   ![image](https://user-images.githubusercontent.com/7137528/96506396-d7635c80-1257-11eb-9389-2dcc24c22597.png)
1. Export as VCS
1. Build from source
1. Go to VBE, see that the references are not the same:
  ![image](https://user-images.githubusercontent.com/7137528/96506357-c4e92300-1257-11eb-9fec-9b92d8d558a6.png)

Looking in the `vbe-references.json` file, I can see that, for the `Microsoft Office 16 Object Library` part:
```json
{
  "Items": {
    "Office": {
      "GUID": "{2DF8D04C-5BFA-101B-BDE5-00AA0044DE52}",
      "Version": "2.8"
    }
  }
}
```

But after building from source, it was changed to 2.6 (but same GUID!):
```json
{
  "Items": {
    "Office": {
      "GUID": "{2DF8D04C-5BFA-101B-BDE5-00AA0044DE52}",
      "Version": "2.6"
    }
  }
}
```

Thank you 😺

**Comment by joyfullservice** [comment]
I am glad to hear of your interest in the project! Please feel free to fork it and create pull requests for fixes/enhancements that you would like to see added.  😄  There are a few key contributors that have really taken this project to the next level. Unicode compatibility and build-from-source are two key features that were implemented recently in collaboration with other developers on this project.

To address the issues mentioned here, let me comment on them in turn.

**Default References:**
Since different versions of Microsoft Access will have different default references, I took the approach of only recording and adding the ones that were not built-in references. This way you can build a project from source (in most cases) even when you are using a different version of Microsoft Access. To remove unwanted references, you could include a script in your project to run after a successful build. (See the [Run Sub After Build](https://github.com/joyfullservice/msaccess-vcs-integration/wiki/Documentation) option here.)

**Office Library Version**
Somewhat similar to above, this is a compatibility issue. The goal is to be able to build a project with any Access version from 2010+ without errors. You can see a few notes below, taken from `clsDbVbeReference`

```
'---------------------------------------------------------------------------------------
' Procedure : AddFromGuid
' Author    : Adam Waller
' Date      : 5/26/2020
' Purpose   : Return a GUID compatible with Access 2010, the lowest targeted version.
'           : Only add references here when they cause compile errors on Access 2010.
'           : Further reading: https://stackoverflow.com/questions/45088306
'---------------------------------------------------------------------------------------
'
Private Sub AddFromGuid(proj As VBIDE.VBProject, strGuid As String, lngMajor As Long, lngMinor As Long)

    Select Case strGuid
        Case "{2DF8D04C-5BFA-101B-BDE5-00AA0044DE52}"   ' Office 2.8 => Office 2.5
            proj.References.AddFromGuid "{2DF8D04C-5BFA-101B-BDE5-00AA0044DE52}", 2, 5
        Case Else
            ' Use specified GUID
            proj.References.AddFromGuid strGuid, lngMajor, lngMinor
    End Select

End Sub
```

With this approach, I am able to build from source in Access 2010 a project that was exported from Access 2019. If this causes undesirable side-affects, we could also consider a backwards-compatibility option that would only do this substitution for projects intended to be compiled on older versions of Microsoft Access. (Such as this add-in project, which I actively develop using Access 2010.)

**Comment by Indigo744** [comment]
**Default References**: I kind of understand, but only two references are really built-in (with the BuiltIn flag set) how do you identify these as built-in?

**Office Library Version**: I understand. But would it be possible to detect if the Office version hasn't changed, and keep the original version Major/minor set? Because as you can see, it changes completely the reference...
For instance, 
- if exporting with Access 2016 and importing in Access 2016, it shouldn't change anything.
- if exporting with Access 2016 and importing in Access 2010, it should drop one or two version
- and so on...?

**Comment by joyfullservice** [comment]
Good thoughts! I have added some additional code to set the reference version number based on the running version of Microsoft Access.

**Comment by Indigo744** [comment]
Perfect! Thanks!
