### ISSUE TITLE
Error 3035: System ressource exceeded

### ISSUE THREAD

**Issue by maddhin** [joyfullservice/msaccess-vcs-integration#77]
Hi,

when trying to rebuild, I am getting error 3035 "system ressource exceeded". The problematic line is 

`cCategory.Import CStr(varFile)` in the Build function. 

I have never used this Add-in and it is the first time I am using it. 

I am not quite sure what this error means but it seems to be a fundamental error in the build function. 

Anybody any idea how to fix this? My VBA skills are still quite fresh - 6 months and counting... 

A different but related question: is this Add-in in sync with the msaccess-vcs-integration master? I am quite a newbie in terms of version control, Git(Hub) AND Access, so I actually would like to work with comparably solid software to not having to debug each of those LOL I love this Add-in fork though which seems perfect for people like me. 

Cheers!

**Comment by Indigo744** [comment]
I'll let @joyfullservice properly answer, but just to chime in: I got similar memory issues when activating the option _Show Detailed Output_ so maybe you have the same problem?
![image](https://user-images.githubusercontent.com/7137528/97035243-544b4a80-1566-11eb-9fa5-146aee2ad656.png)

**Comment by joyfullservice** [comment]
@maddhin - Thanks for the feedback! Some more specific details would be helpful in pinpointing the error, but setting the following VBA Option should help.

![image](https://user-images.githubusercontent.com/7254992/97042364-8775e580-1536-11eb-9d3d-d41e5ef262bc.png)

I recognize your desire for solid, robust software tools. We all like them!  😄  As an open-source project, this tool is made available by people that have donated their time and effort to make it available to others. The benefit is that the collaborative volunteer development can propel the project further along than one person just doing it by themselves, but the drawback is that no person is being paid to work through all the bugs and provide professional support services. 

I suppose you could always hire a another consultant to work through specific issues and create pull requests to merge into the core software, but most of the contributors to this project have been developers that use the tool for their own purposes, and contribute various features that benefit the specific areas relevant to them.

With regard to the difference between this project and the original fork, I would say that this fork has undergone extensive rewriting and improvement (I have personally invested hundreds of hours in the project) that makes it very different today from the original timabel fork, (now msaccess-vcs-integration/msaccess-vcs-integration). There are no plans to ever merge this fork back into the original parent project since the two are so significantly different now.

I hope that helps!
