### ISSUE TITLE
Table data import unnecessarily deletes and recreates tables

### ISSUE THREAD

**Issue by coderGoneOffRoad** [joyfullservice/msaccess-vcs-integration#90]
I was having trouble importing data. The error was that the data does not fit into table. I did debug and found out that in table import the table was created properly according to the table definition. However in the consecutive table data import phase the table is deleted and recreated based on the tabledata-xml. This tabledata-xml does not contain any definition for table structure and hence the table size will be some default setting (255 chars or so). 

I fixed this by altering the table data import so that it does not delete the table but instead only imports data to existing table.

![image](https://user-images.githubusercontent.com/73994727/99075435-2768e100-25c2-11eb-8ed8-40bd5368d50f.png)

**Comment by joyfullservice** [comment]
That looks like an older version of the function... Which version of the add-in are you using? This was fixed in v3.2.0 which rolled out last week. You can find the latest version on the [releases](https://github.com/joyfullservice/msaccess-vcs-integration/releases) page, or build the add-in from source to get the very latest updates.
